/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { AccountServiceAuthenticationTypes } from './AccountServiceAuthenticationTypes';
import type { ResourceOem } from './ResourceOem';

/**
 * The information required to authenticate to the external service.
 * @version 1.18.1
 */
export interface AccountServiceAuthentication {
    /**
     * The type of authentication used to connect to the external account provider.
     * @nullable
     */
    AuthenticationType?: AccountServiceAuthenticationTypes;
    /**
     * Specifies the encryption key.
     * @nullable
     * @pattern ^[0-9a-fA-F]+$
     */
    EncryptionKey?: string | null;
    /**
     * Indicates if the `EncryptionKey` property is set.
     * @nullable
     */
    readonly EncryptionKeySet?: boolean | null;
    /**
     * The Base64-encoded Kerberos keytab for this service.  A `PATCH` or `PUT` operation writes the keytab.  This property is `null` in responses.
     * @nullable
     */
    KerberosKeytab?: string | null;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The password for this service.  A `PATCH` or `PUT` request writes the password.  This property is `null` in responses.
     * @nullable
     */
    Password?: string | null;
    /**
     * The token for this service.  A `PATCH` or `PUT` operation writes the token.  This property is `null` in responses.
     * @nullable
     */
    Token?: string | null;
    /** The username for the service. */
    Username?: string;
}
