/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { AccountServiceActions } from './AccountServiceActions';
import type { AccountServiceExternalAccountProvider } from './AccountServiceExternalAccountProvider';
import type { ResourceDescription } from './ResourceDescription';
import type { AccountServiceBasicAuthState } from './AccountServiceBasicAuthState';
import type { ResourceId } from './ResourceId';
import type { AccountServiceLocalAccountAuth } from './AccountServiceLocalAccountAuth';
import type { AccountServiceMultiFactorAuth } from './AccountServiceMultiFactorAuth';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';
import type { PrivilegesPrivilegeType } from './PrivilegesPrivilegeType';
import type { ResourceStatus } from './ResourceStatus';
import type { ManagerAccountAccountTypes } from './ManagerAccountAccountTypes';

/**
 * The `AccountService` schema defines an account service.  The properties are common to, and enable management of, all user accounts.  The properties include the password requirements and control features, such as account lockout.  Properties and actions in this service specify general behavior that should be followed for typical accounts, however implementations might override these behaviors for special accounts or situations to avoid denial of service or other deadlock situations.
 * @version 1.18.1
 */
export interface AccountService {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /**
     * The period of time, in seconds, between the last failed login attempt and the reset of the lockout threshold counter.  This value must be less than or equal to the `AccountLockoutDuration` value.  A reset sets the counter to `0`.
     * @minimum 0
     */
    AccountLockoutCounterResetAfter?: number;
    /** An indication of whether the threshold counter is reset after `AccountLockoutCounterResetAfter` expires.  If `true`, it is reset.  If `false`, only a successful login resets the threshold counter and if the user reaches the `AccountLockoutThreshold` limit, the account will be locked out indefinitely and only an administrator-issued reset clears the threshold counter.  If this property is absent, the default is `true`. */
    AccountLockoutCounterResetEnabled?: boolean;
    /**
     * The period of time, in seconds, that an account is locked after the number of failed login attempts reaches the account lockout threshold, within the period between the last failed login attempt and the reset of the lockout threshold counter.  If this value is `0`, no lockout will occur.  If the `AccountLockoutCounterResetEnabled` value is `false`, this property is ignored.
     * @minimum 0
     * @nullable
     */
    AccountLockoutDuration?: number | null;
    /**
     * The number of allowed failed login attempts before a user account is locked for a specified duration.  If `0`, the account is never locked.
     * @minimum 0
     * @nullable
     */
    AccountLockoutThreshold?: number | null;
    /** The collection of manager accounts. */
    readonly Accounts?: OdataV4IdRef;
    /** The available actions for this resource. */
    Actions?: AccountServiceActions;
    /** The first Active Directory external account provider that this account service supports. */
    ActiveDirectory?: AccountServiceExternalAccountProvider;
    /** The additional external account providers that this account service uses. */
    readonly AdditionalExternalAccountProviders?: OdataV4IdRef;
    /**
     * The number of authorization failures per account that are allowed before the failed attempt is logged to the manager log.
     * @minimum 0
     */
    AuthFailureLoggingThreshold?: number;
    /** @nullable */
    readonly Description?: ResourceDescription;
    /**
     * The number of unique new passwords that need to be associated with a user account before a previous password is accepted when modifying the password.  If `0`, a user does not need to provide a unique new password.
     * @minimum 0
     */
    EnforcePasswordHistoryCount?: number;
    /**
     * Indicates if HTTP Basic authentication is enabled for this service.
     * @nullable
     */
    HTTPBasicAuth?: AccountServiceBasicAuthState;
    readonly Id: ResourceId;
    /** The first LDAP external account provider that this account service supports. */
    LDAP?: AccountServiceExternalAccountProvider;
    /** An indication of how the service uses the accounts collection within this account service as part of authentication.  The enumerated values describe the details for each mode. */
    LocalAccountAuth?: AccountServiceLocalAccountAuth;
    /**
     * The maximum password length for this account service.
     * @minimum 0
     */
    MaxPasswordLength?: number;
    /**
     * The minimum password length for this account service.
     * @minimum 0
     */
    MinPasswordLength?: number;
    /**
     * The multi-factor authentication settings that this account service supports.
     * @nullable
     */
    MultiFactorAuth?: AccountServiceMultiFactorAuth;
    readonly Name: ResourceName;
    /**
     * The first OAuth 2.0 external account provider that this account service supports.
     * @nullable
     */
    OAuth2?: AccountServiceExternalAccountProvider;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The collection of outbound connection configurations.
     * @nullable
     */
    OutboundConnections?: OdataV4IdRef;
    /**
     * The number of days before account passwords in this account service will expire.
     * @nullable
     */
    PasswordExpirationDays?: number | null;
    /** Password creation guidance for manager accounts. */
    readonly PasswordGuidanceMessage?: string;
    /**
     * A `MessageId` that contains password creation guidance for manager accounts.
     * @nullable
     */
    readonly PasswordGuidanceMessageId?: string | null;
    /** The link to the mapping of the privileges required to complete a requested operation on a URI associated with this service. */
    readonly PrivilegeMap?: OdataV4IdRef;
    /**
     * An indication of whether clients are required to invoke the `ChangePassword` action to modify account passwords.
     * @nullable
     */
    RequireChangePasswordAction?: boolean | null;
    /** The set of restricted OEM privileges. */
    readonly RestrictedOemPrivileges?: readonly string[];
    /** The set of restricted Redfish privileges. */
    readonly RestrictedPrivileges?: readonly PrivilegesPrivilegeType[];
    /** The collection of Redfish roles. */
    readonly Roles?: OdataV4IdRef;
    /**
     * An indication of whether the account service is enabled.  If `true`, it is enabled.  If `false`, it is disabled and users cannot be created, deleted, or modified, and new sessions cannot be started.  However, established sessions might still continue to run.  Any service, such as the session service, that attempts to access the disabled account service fails.  However, this does not affect HTTP Basic Authentication connections.
     * @nullable
     */
    ServiceEnabled?: boolean | null;
    /** The status and health of the resource and its subordinate or dependent resources. */
    Status?: ResourceStatus;
    /** The account types supported by the service. */
    readonly SupportedAccountTypes?: readonly ManagerAccountAccountTypes[];
    /** The OEM account types supported by the service. */
    readonly SupportedOEMAccountTypes?: readonly string[];
    /**
     * The first TACACS+ external account provider that this account service supports.
     * @nullable
     */
    TACACSplus?: AccountServiceExternalAccountProvider;
}
