/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { AccountServiceOAuth2Mode } from './AccountServiceOAuth2Mode';
import type { ResourceOem } from './ResourceOem';

/**
 * Various settings to parse an OAuth 2.0 service.
 * @version 1.18.1
 */
export interface AccountServiceOAuth2Service {
    /** The allowable audience strings of the Redfish service. */
    readonly Audience?: readonly string[];
    /**
     * The issuer string of the OAuth 2.0 service.  Clients should configure this property if `Mode` contains `Offline`.
     * @nullable
     */
    Issuer?: string | null;
    /** The mode of operation for token validation. */
    Mode?: AccountServiceOAuth2Mode;
    /**
     * The Base64-encoded signing keys of the issuer of the OAuth 2.0 service.  Clients should configure this property if `Mode` contains `Offline`.
     * @nullable
     */
    OAuthServiceSigningKeys?: string | null;
    /** The OEM extension property. */
    Oem?: ResourceOem;
}
