/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

export type AccountServiceMFABypassType =
    (typeof AccountServiceMFABypassType)[keyof typeof AccountServiceMFABypassType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountServiceMFABypassType = {
    /** Bypass all multi-factor authentication types. */
    All: 'All',
    /** Bypass RSA SecurID. */
    SecurID: 'SecurID',
    /** Bypass Google Authenticator. */
    GoogleAuthenticator: 'GoogleAuthenticator',
    /** Bypass Microsoft Authenticator. */
    MicrosoftAuthenticator: 'MicrosoftAuthenticator',
    /** Bypass client certificate authentication. */
    ClientCertificate: 'ClientCertificate',
    /** Bypass one-time passcode authentication. */
    OneTimePasscode: 'OneTimePasscode',
    /** Bypass Time-based One-Time Password (TOTP) authentication. */
    TimeBasedOneTimePassword: 'TimeBasedOneTimePassword',
    /** Bypass OEM-defined multi-factor authentication. */
    OEM: 'OEM',
} as const;
