/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { AccountServiceMFABypassType } from './AccountServiceMFABypassType';

/**
 * Multi-factor authentication bypass settings.
 * @version 1.18.1
 */
export interface AccountServiceMFABypass {
    /** The types of multi-factor authentication this account or role mapping is allowed to bypass. */
    BypassTypes?: AccountServiceMFABypassType[];
}
