/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * Various settings for Microsoft Authenticator multi-factor authentication.
 * @version 1.18.1
 */
export interface AccountServiceMicrosoftAuthenticator {
    /**
     * An indication of whether multi-factor authentication with Microsoft Authenticator is enabled.
     * @nullable
     */
    Enabled?: boolean | null;
    /**
     * The secret key to use when communicating with the Microsoft Authenticator server.  This property is `null` in responses.
     * @nullable
     */
    SecretKey?: string | null;
    /** Indicates if the `SecretKey` property is set. */
    readonly SecretKeySet?: boolean;
}
