/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.18.1
 */
export type AccountServiceOAuth2Mode =
    (typeof AccountServiceOAuth2Mode)[keyof typeof AccountServiceOAuth2Mode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountServiceOAuth2Mode = {
    /** OAuth 2.0 service information for token validation is downloaded by the service. */
    Discovery: 'Discovery',
    /** OAuth 2.0 service information for token validation is configured by a client.  Clients should configure the `Issuer` and `OAuthServiceSigningKeys` properties for this mode. */
    Offline: 'Offline',
} as const;
