/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.18.1
 */
export type AccountServiceBasicAuthState =
    (typeof AccountServiceBasicAuthState)[keyof typeof AccountServiceBasicAuthState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountServiceBasicAuthState = {
    /** HTTP Basic authentication is enabled. */
    Enabled: 'Enabled',
    /** HTTP Basic authentication is enabled, but is not advertised with the `WWW-Authenticate` response header. */
    Unadvertised: 'Unadvertised',
    /** HTTP Basic authentication is disabled. */
    Disabled: 'Disabled',
} as const;
