/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { AccountServiceClientCertificate } from './AccountServiceClientCertificate';
import type { AccountServiceGoogleAuthenticator } from './AccountServiceGoogleAuthenticator';
import type { AccountServiceMicrosoftAuthenticator } from './AccountServiceMicrosoftAuthenticator';
import type { AccountServiceOneTimePasscode } from './AccountServiceOneTimePasscode';
import type { AccountServiceSecurID } from './AccountServiceSecurID';
import type { AccountServiceTimeBasedOneTimePassword } from './AccountServiceTimeBasedOneTimePassword';

/**
 * Multi-factor authentication settings.
 * @version 1.18.1
 */
export interface AccountServiceMultiFactorAuth {
    /**
     * The settings related to client certificate authentication schemes such as mTLS or CAC/PIV.
     * @nullable
     */
    ClientCertificate?: AccountServiceClientCertificate;
    /**
     * The settings related to Google Authenticator multi-factor authentication.  For generic Time-Based One-Time Password (TOTP) multi-factor authentication, use the `TimeBasedOneTimePassword` property.
     * @nullable
     */
    GoogleAuthenticator?: AccountServiceGoogleAuthenticator;
    /**
     * The settings related to Microsoft Authenticator multi-factor authentication.  For generic Time-Based One-Time Password (TOTP) multi-factor authentication, use the `TimeBasedOneTimePassword` property.
     * @nullable
     */
    MicrosoftAuthenticator?: AccountServiceMicrosoftAuthenticator;
    /**
     * The settings related to one-time passcode (OTP) multi-factor authentication.
     * @nullable
     */
    OneTimePasscode?: AccountServiceOneTimePasscode;
    /**
     * The settings related to RSA SecurID multi-factor authentication.
     * @nullable
     */
    SecurID?: AccountServiceSecurID;
    /**
     * The settings related to Time-based One-Time Password (TOTP) multi-factor authentication.
     * @nullable
     */
    TimeBasedOneTimePassword?: AccountServiceTimeBasedOneTimePassword;
}
