/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { AccountServiceCertificateMappingAttribute } from './AccountServiceCertificateMappingAttribute';
import type { OdataV4IdRef } from './OdataV4IdRef';

/**
 * Various settings for client certificate authentication such as mTLS or CAC/PIV.
 * @version 1.18.1
 */
export interface AccountServiceClientCertificate {
    /**
     * The client certificate attribute to map to a user.
     * @nullable
     */
    CertificateMappingAttribute?: AccountServiceCertificateMappingAttribute;
    /** The link to a collection of CA certificates used to validate client certificates. */
    readonly Certificates?: OdataV4IdRef;
    /**
     * An indication of whether client certificate authentication is enabled.
     * @nullable
     */
    Enabled?: boolean | null;
    /**
     * An indication of whether the service responds to clients that do not successfully authenticate.
     * @nullable
     */
    RespondToUnauthenticatedClients?: boolean | null;
}
