/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceOem } from './ResourceOem';
import type { AccountServiceTACACSplusPasswordExchangeProtocol } from './AccountServiceTACACSplusPasswordExchangeProtocol';

/**
 * Various settings to parse a TACACS+ service.
 * @version 1.18.1
 */
export interface AccountServiceTACACSplusService {
    /** The TACACS+ service authorization argument. */
    AuthorizationService?: string;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** Indicates the allowed TACACS+ password exchange protocols. */
    PasswordExchangeProtocols?: AccountServiceTACACSplusPasswordExchangeProtocol[];
    /**
     * Indicates the name of the TACACS+ argument name in an authorization request.
     * @nullable
     */
    PrivilegeLevelArgument?: string | null;
}
