/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.18.1
 */
export type AccountServiceCertificateMappingAttribute =
    (typeof AccountServiceCertificateMappingAttribute)[keyof typeof AccountServiceCertificateMappingAttribute];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountServiceCertificateMappingAttribute = {
    /** Match the whole certificate. */
    Whole: 'Whole',
    /** Match the Common Name (CN) field in the provided certificate to the username. */
    CommonName: 'CommonName',
    /** Match the User Principal Name (UPN) field in the provided certificate to the username. */
    UserPrincipalName: 'UserPrincipalName',
} as const;
