/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * Various settings for Time-based One-Time Password (TOTP) multi-factor authentication.
 * @version 1.18.1
 */
export interface AccountServiceTimeBasedOneTimePassword {
    /**
     * An indication of whether multi-factor authentication with a Time-based One-Time Password (TOTP) is enabled.
     * @nullable
     */
    Enabled?: boolean | null;
    /**
     * The time step, in seconds, for calculating the one-time password.
     * @minimum 1
     * @nullable
     */
    TimeStepSeconds?: number | null;
}
