/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceOem } from './ResourceOem';
import type { AccountServiceLDAPSearchSettings } from './AccountServiceLDAPSearchSettings';

/**
 * The settings required to parse a generic LDAP service.
 * @version 1.18.1
 */
export interface AccountServiceLDAPService {
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** The required settings to search an external LDAP service. */
    SearchSettings?: AccountServiceLDAPSearchSettings;
}
