/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.18.1
 */
export type AccountServiceTACACSplusPasswordExchangeProtocol =
    (typeof AccountServiceTACACSplusPasswordExchangeProtocol)[keyof typeof AccountServiceTACACSplusPasswordExchangeProtocol];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountServiceTACACSplusPasswordExchangeProtocol = {
    /** The ASCII Login method. */
    ASCII: 'ASCII',
    /** The PAP Login method. */
    PAP: 'PAP',
    /** The CHAP Login method. */
    CHAP: 'CHAP',
    /** The MS-CHAP v1 Login method. */
    MSCHAPv1: 'MSCHAPv1',
    /** The MS-CHAP v2 Login method. */
    MSCHAPv2: 'MSCHAPv2',
} as const;
