/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * Various settings for one-time passcode (OTP) multi-factor authentication.
 * @version 1.18.1
 */
export interface AccountServiceOneTimePasscode {
    /**
     * An indication of whether multi-factor authentication using a one-time passcode is enabled.
     * @nullable
     */
    Enabled?: boolean | null;
}
