/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.18.1
 */
export type AccountServiceAccountProviderTypes =
    (typeof AccountServiceAccountProviderTypes)[keyof typeof AccountServiceAccountProviderTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountServiceAccountProviderTypes = {
    /** An external Redfish service. */
    RedfishService: 'RedfishService',
    /** An external Active Directory service. */
    ActiveDirectoryService: 'ActiveDirectoryService',
    /** A generic external LDAP service. */
    LDAPService: 'LDAPService',
    /** An OEM-specific external authentication or directory service. */
    OEM: 'OEM',
    /** An external TACACS+ service. */
    TACACSplus: 'TACACSplus',
    /** An external OAuth 2.0 service. */
    OAuth2: 'OAuth2',
} as const;
