/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { AccountServiceAccountProviderTypes } from './AccountServiceAccountProviderTypes';
import type { AccountServiceAuthentication } from './AccountServiceAuthentication';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { AccountServiceLDAPService } from './AccountServiceLDAPService';
import type { AccountServiceOAuth2Service } from './AccountServiceOAuth2Service';
import type { AccountServiceRoleMapping } from './AccountServiceRoleMapping';
import type { AccountServiceTACACSplusService } from './AccountServiceTACACSplusService';

/**
 * The external account provider services that can provide accounts for this manager to use for authentication.
 * @version 1.18.1
 */
export interface AccountServiceExternalAccountProvider {
    /**
     * The type of external account provider to which this service connects.
     * @deprecated
     * @nullable
     */
    readonly AccountProviderType?: AccountServiceAccountProviderTypes;
    /** The authentication information for the external account provider. */
    Authentication?: AccountServiceAuthentication;
    /** The link to a collection of certificates that the external account provider uses. */
    readonly Certificates?: OdataV4IdRef;
    /** The additional mapping information needed to parse a generic LDAP service. */
    LDAPService?: AccountServiceLDAPService;
    /**
     * The additional information needed to parse an OAuth 2.0 service.
     * @nullable
     */
    OAuth2Service?: AccountServiceOAuth2Service;
    /** Indicates if the `Password` property is set. */
    readonly PasswordSet?: boolean;
    /**
     * The authentication priority for the external account provider.
     * @minimum 0
     * @nullable
     */
    Priority?: number | null;
    /** The mapping rules to convert the external account providers account information to the local Redfish role. */
    RemoteRoleMapping?: AccountServiceRoleMapping[];
    /**
     * The number of times to retry connecting to an address in the `ServiceAddresses` property before attempting the next address in the array.
     * @nullable
     */
    Retries?: number | null;
    /** The addresses of the user account providers to which this external account provider links.  The format of this field depends on the type of external account provider. */
    ServiceAddresses?: (string | null)[];
    /**
     * An indication of whether this service is enabled.
     * @nullable
     */
    ServiceEnabled?: boolean | null;
    /**
     * The additional information needed to parse a TACACS+ services.
     * @nullable
     */
    TACACSplusService?: AccountServiceTACACSplusService;
    /**
     * The period of time, in seconds, this account service will wait for a response from an address of a user account provider before timing out.
     * @nullable
     */
    TimeoutSeconds?: number | null;
}
