/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The settings to search a generic LDAP service.
 * @version 1.18.1
 */
export interface AccountServiceLDAPSearchSettings {
    /** The base distinguished names to use to search an external LDAP service. */
    BaseDistinguishedNames?: (string | null)[];
    /**
     * The attribute name that contains the LDAP user's email address.
     * @nullable
     */
    EmailAttribute?: string | null;
    /**
     * The attribute name that contains the LDAP group name entry.
     * @nullable
     */
    GroupNameAttribute?: string | null;
    /**
     * The attribute name that contains the groups for a user on the LDAP user entry.
     * @nullable
     */
    GroupsAttribute?: string | null;
    /**
     * The attribute name that contains the LDAP user's SSH public key entry.
     * @nullable
     */
    SSHKeyAttribute?: string | null;
    /**
     * The attribute name that contains the LDAP username entry.
     * @nullable
     */
    UsernameAttribute?: string | null;
}
