/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.18.1
 */
export type AccountServiceLocalAccountAuth =
    (typeof AccountServiceLocalAccountAuth)[keyof typeof AccountServiceLocalAccountAuth];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountServiceLocalAccountAuth = {
    /** The service authenticates users based on the account service-defined accounts collection. */
    Enabled: 'Enabled',
    /** The service never authenticates users based on the account service-defined accounts collection. */
    Disabled: 'Disabled',
    /** The service authenticates users based on the account service-defined accounts collection only if any external account providers are currently unreachable. */
    Fallback: 'Fallback',
    /** The service first authenticates users based on the account service-defined accounts collection.  If authentication fails, the service authenticates by using external account providers. */
    LocalFirst: 'LocalFirst',
} as const;
