/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.18.1
 */
export type AccountServiceAuthenticationTypes =
    (typeof AccountServiceAuthenticationTypes)[keyof typeof AccountServiceAuthenticationTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountServiceAuthenticationTypes = {
    /** An opaque authentication token. */
    Token: 'Token',
    /** A Kerberos keytab. */
    KerberosKeytab: 'KerberosKeytab',
    /** A username and password combination. */
    UsernameAndPassword: 'UsernameAndPassword',
    /** An OEM-specific authentication mechanism. */
    OEM: 'OEM',
} as const;
