/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ManagerAccountAccountTypes } from './ManagerAccountAccountTypes';
import type { AccountServiceMFABypass } from './AccountServiceMFABypass';
import type { ResourceOem } from './ResourceOem';

/**
 * The mapping rules that are used to convert the external account providers account information to the local Redfish role.
 * @version 1.18.1
 */
export interface AccountServiceRoleMapping {
    /** The list of local services in the manager that the remote user or group is allowed to access. */
    LocalAccountTypes?: ManagerAccountAccountTypes[];
    /** The OEM account types for the remote user or group. */
    LocalOEMAccountTypes?: (string | null)[];
    /**
     * The name of the local Redfish role to which to map the remote user or group.
     * @nullable
     */
    LocalRole?: string | null;
    /**
     * The multi-factor authentication bypass settings.
     * @nullable
     */
    MFABypass?: AccountServiceMFABypass;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The name of the remote group, or the remote role in the case of a Redfish service, that maps to the local Redfish role to which this entity links.
     * @nullable
     */
    RemoteGroup?: string | null;
    /**
     * The name of the remote user that maps to the local Redfish role to which this entity links.
     * @nullable
     */
    RemoteUser?: string | null;
}
