/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4IdRef } from './OdataV4IdRef';

/**
 * Various settings for RSA SecurID multi-factor authentication.
 * @version 1.18.1
 */
export interface AccountServiceSecurID {
    /** The link to a collection of server certificates for the RSA SecurID server referenced by the `ServerURI` property. */
    readonly Certificates?: OdataV4IdRef;
    /**
     * The client ID to use when communicating with the RSA SecurID server.
     * @nullable
     */
    ClientId?: string | null;
    /**
     * The client secret to use when communicating with the RSA SecurID server.  This property is `null` in responses.
     * @nullable
     */
    ClientSecret?: string | null;
    /** Indicates if the `ClientSecret` property is set. */
    readonly ClientSecretSet?: boolean;
    /**
     * An indication of whether multi-factor authentication with RSA SecurID is enabled.
     * @nullable
     */
    Enabled?: boolean | null;
    /**
     * The URI of the RSA SecurID server.
     * @nullable
     */
    ServerURI?: string | null;
}
