/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.5.0
 */
export type ActionInfoParameterTypes =
    (typeof ActionInfoParameterTypes)[keyof typeof ActionInfoParameterTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionInfoParameterTypes = {
    /** A boolean. */
    Boolean: 'Boolean',
    /** A number. */
    Number: 'Number',
    /** An array of numbers. */
    NumberArray: 'NumberArray',
    /** A string. */
    String: 'String',
    /** An array of strings. */
    StringArray: 'StringArray',
    /** An embedded JSON object. */
    Object: 'Object',
    /** An array of JSON objects. */
    ObjectArray: 'ObjectArray',
} as const;
