/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ActionInfoParameterTypes } from './ActionInfoParameterTypes';

/**
 * The information about a parameter included in a Redfish action for this resource.
 * @version 1.5.0
 */
export interface ActionInfoParameters {
    /** The allowable numeric values or duration values, inclusive ranges of values, and incremental step values for this parameter as applied to this action target. */
    readonly AllowableNumbers?: readonly (string | null)[];
    /**
     * The allowable pattern for this parameter as applied to this action target.
     * @nullable
     */
    readonly AllowablePattern?: string | null;
    /** Descriptions of allowable values for this parameter. */
    readonly AllowableValueDescriptions?: readonly (string | null)[];
    /** The allowable values for this parameter as applied to this action target. */
    readonly AllowableValues?: readonly (string | null)[];
    /**
     * The maximum number of array elements allowed for this parameter.
     * @nullable
     */
    readonly ArraySizeMaximum?: number | null;
    /**
     * The minimum number of array elements required for this parameter.
     * @nullable
     */
    readonly ArraySizeMinimum?: number | null;
    /**
     * The JSON property type for this parameter.
     * @nullable
     */
    readonly DataType?: ActionInfoParameterTypes;
    /**
     * The default value for this parameter.
     * @nullable
     */
    readonly DefaultValue?: string | null;
    /**
     * The maximum supported value for this parameter.
     * @nullable
     */
    readonly MaximumValue?: number | null;
    /**
     * The minimum supported value for this parameter.
     * @nullable
     */
    readonly MinimumValue?: number | null;
    /** The name of the parameter for this action. */
    readonly Name: string;
    /**
     * Indicates that there is no default value for this parameter.
     * @nullable
     */
    readonly NoDefaultValue?: boolean | null;
    /**
     * The data type of an object-based parameter.
     * @nullable
     */
    readonly ObjectDataType?: string | null;
    /** An indication of whether the parameter is required to complete this action. */
    readonly Required?: boolean;
}
