/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

export type ManagerAccountAccountTypes =
    (typeof ManagerAccountAccountTypes)[keyof typeof ManagerAccountAccountTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManagerAccountAccountTypes = {
    /** Allow access to the Redfish service. */
    Redfish: 'Redfish',
    /** Allow access to SNMP services. */
    SNMP: 'SNMP',
    /** OEM account type.  See the `OEMAccountTypes` property. */
    OEM: 'OEM',
    /** Allow access to the host\'s console, which could be connected through Telnet, SSH, or another protocol. */
    HostConsole: 'HostConsole',
    /** Allow access to the manager\'s console, which could be connected through Telnet, SSH, SM CLP, or another protocol. */
    ManagerConsole: 'ManagerConsole',
    /** Allow access to the Intelligent Platform Management Interface service. */
    IPMI: 'IPMI',
    /** Allow access to a Keyboard-Video-Mouse over IP session. */
    KVMIP: 'KVMIP',
    /** Allow access to control virtual media. */
    VirtualMedia: 'VirtualMedia',
    /** Allow access to a web user interface session, such as a graphical interface or another web-based protocol. */
    WebUI: 'WebUI',
    /** Allow PIN-based access via an external control panel, such as a keypad, touchscreen, or other human interface. */
    ControlPanel: 'ControlPanel',
} as const;
