/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Id } from './OdataV4Id';

/**
 * A reference to a resource.
 */
export interface OdataV4IdRef {
    '@odata.id'?: OdataV4Id;
}
