/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

export type PhysicalContextPhysicalSubContext =
    (typeof PhysicalContextPhysicalSubContext)[keyof typeof PhysicalContextPhysicalSubContext];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PhysicalContextPhysicalSubContext = {
    /** The input. */
    Input: 'Input',
    /** The output. */
    Output: 'Output',
} as const;
