/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

export type PhysicalContext =
    (typeof PhysicalContext)[keyof typeof PhysicalContext];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PhysicalContext = {
    /** The room. */
    Room: 'Room',
    /** The air intake point or points or region of the chassis. */
    Intake: 'Intake',
    /** The air exhaust point or points or region of the chassis. */
    Exhaust: 'Exhaust',
    /** The liquid inlet point of the chassis. */
    LiquidInlet: 'LiquidInlet',
    /** The liquid outlet point of the chassis. */
    LiquidOutlet: 'LiquidOutlet',
    /** The front of the chassis. */
    Front: 'Front',
    /** The back of the chassis. */
    Back: 'Back',
    /** The upper portion of the chassis. */
    Upper: 'Upper',
    /** The lower portion of the chassis. */
    Lower: 'Lower',
    /** A processor (CPU). */
    CPU: 'CPU',
    /** The entire processor (CPU) subsystem. */
    CPUSubsystem: 'CPUSubsystem',
    /** A graphics processor (GPU). */
    GPU: 'GPU',
    /** The entire graphics processor (GPU) subsystem. */
    GPUSubsystem: 'GPUSubsystem',
    /** An FPGA. */
    FPGA: 'FPGA',
    /** An accelerator. */
    Accelerator: 'Accelerator',
    /** An ASIC device, such as a networking chip or chipset component. */
    ASIC: 'ASIC',
    /** A backplane within the chassis. */
    Backplane: 'Backplane',
    /** The system board (PCB). */
    SystemBoard: 'SystemBoard',
    /** A power supply. */
    PowerSupply: 'PowerSupply',
    /** The entire power subsystem. */
    PowerSubsystem: 'PowerSubsystem',
    /** A voltage regulator device. */
    VoltageRegulator: 'VoltageRegulator',
    /** A rectifier device. */
    Rectifier: 'Rectifier',
    /** A storage device. */
    StorageDevice: 'StorageDevice',
    /** A storage subsystem. */
    StorageSubsystem: 'StorageSubsystem',
    /** A networking device. */
    NetworkingDevice: 'NetworkingDevice',
    /** A group of expansion bays. */
    ExpansionSubsystem: 'ExpansionSubsystem',
    /** A compute bay. */
    ComputeBay: 'ComputeBay',
    /** A storage bay. */
    StorageBay: 'StorageBay',
    /** A networking bay. */
    NetworkBay: 'NetworkBay',
    /** An expansion bay. */
    ExpansionBay: 'ExpansionBay',
    /** A power supply bay. */
    PowerSupplyBay: 'PowerSupplyBay',
    /** A memory device. */
    Memory: 'Memory',
    /** The entire memory subsystem. */
    MemorySubsystem: 'MemorySubsystem',
    /** The entire chassis. */
    Chassis: 'Chassis',
    /** A fan. */
    Fan: 'Fan',
    /** The entire cooling, or air and liquid, subsystem. */
    CoolingSubsystem: 'CoolingSubsystem',
    /** A motor. */
    Motor: 'Motor',
    /** A transformer. */
    Transformer: 'Transformer',
    /** An AC electrical utility input. */
    ACUtilityInput: 'ACUtilityInput',
    /** An AC electrical static bypass input. */
    ACStaticBypassInput: 'ACStaticBypassInput',
    /** An AC electrical maintenance bypass input. */
    ACMaintenanceBypassInput: 'ACMaintenanceBypassInput',
    /** A DC electrical bus. */
    DCBus: 'DCBus',
    /** An AC electrical output or output-related circuit. */
    ACOutput: 'ACOutput',
    /** An AC electrical input or input-related circuit. */
    ACInput: 'ACInput',
    /** An electrical outlet. */
    PowerOutlet: 'PowerOutlet',
    /** A trusted module. */
    TrustedModule: 'TrustedModule',
    /** A circuit board. */
    Board: 'Board',
    /** A transceiver. */
    Transceiver: 'Transceiver',
    /** A battery. */
    Battery: 'Battery',
    /** A pump. */
    Pump: 'Pump',
    /** A filter. */
    Filter: 'Filter',
    /** A reservoir. */
    Reservoir: 'Reservoir',
    /** A switch device. */
    Switch: 'Switch',
    /** A management controller, such as a BMC (baseboard management controller). */
    Manager: 'Manager',
} as const;
