/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

export type PrivilegesPrivilegeType =
    (typeof PrivilegesPrivilegeType)[keyof typeof PrivilegesPrivilegeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PrivilegesPrivilegeType = {
    /** Can log in to the service and read resources. */
    Login: 'Login',
    /** Can configure managers. */
    ConfigureManager: 'ConfigureManager',
    /** Can configure users and their accounts. */
    ConfigureUsers: 'ConfigureUsers',
    /** Can change the password for the current user account, log out of their own sessions, and perform operations on resources they created.  Services will need to be aware of resource ownership to map this privilege to an operation from a particular user. */
    ConfigureSelf: 'ConfigureSelf',
    /** Can configure components that this service manages. */
    ConfigureComponents: 'ConfigureComponents',
    /** Authentication is not required. */
    NoAuth: 'NoAuth',
    /** Can view and configure composition service resources. */
    ConfigureCompositionInfrastructure: 'ConfigureCompositionInfrastructure',
    /** Administrator for systems found in the systems collection.  Able to manage boot configuration, keys, and certificates for systems. */
    AdministrateSystems: 'AdministrateSystems',
    /** Operator for systems found in the systems collection.  Able to perform resets and configure interfaces. */
    OperateSystems: 'OperateSystems',
    /** Administrator for storage subsystems and storage systems found in the storage collection and storage system collection respectively. */
    AdministrateStorage: 'AdministrateStorage',
    /** Operator for storage backup functionality for storage subsystems and storage systems found in the storage collection and storage system collection respectively. */
    OperateStorageBackup: 'OperateStorageBackup',
} as const;
