/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.7.0
 */
export type RedundancyType =
    (typeof RedundancyType)[keyof typeof RedundancyType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RedundancyType = {
    /** Failure of one unit automatically causes a standby or offline unit in the redundancy set to take over its functions. */
    Failover: 'Failover',
    /** Multiple units are available and active such that normal operation will continue if one or more units fail. */
    NPlusM: 'NPlusM',
    /** Multiple units contribute or share such that operation will continue, but at a reduced capacity, if one or more units fail. */
    Sharing: 'Sharing',
    /** One or more spare units are available to take over the function of a failed unit, but takeover is not automatic. */
    Sparing: 'Sparing',
    /** The subsystem is not configured in a redundancy mode, either due to configuration or the functionality has been disabled by the user. */
    NotRedundant: 'NotRedundant',
} as const;
