/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { OdataV4Count } from './OdataV4Count';
import type { RedundancyType } from './RedundancyType';
import type { ResourceStatus } from './ResourceStatus';

/**
 * The redundancy information for the devices in a redundancy group.
 * @version 1.7.0
 */
export interface RedundancyRedundantGroup {
    /** The links to the active members included in this redundancy group. */
    readonly ActiveRedundancyGroup?: readonly OdataV4IdRef[];
    'ActiveRedundancyGroup@odata.count'?: OdataV4Count;
    /** The name of the redundant group. */
    readonly GroupName?: string;
    /**
     * The maximum number of devices supported in this redundancy group.
     * @nullable
     */
    readonly MaxSupportedInGroup?: number | null;
    /**
     * The minimum number of devices needed for this group to be redundant.
     * @nullable
     */
    readonly MinNeededForFaultTolerance?: number | null;
    /**
     * The minimum number of devices needed for this group to remain operational or functional.
     * @nullable
     */
    readonly MinNeededInGroup: number | null;
    /** The links to the devices included in this redundancy group. */
    readonly RedundancyGroup: readonly OdataV4IdRef[];
    'RedundancyGroup@odata.count'?: OdataV4Count;
    /**
     * The redundancy mode of the group.
     * @nullable
     */
    RedundancyType: RedundancyType;
    /** The status and health of the resource and its subordinate or dependent resources. */
    Status: ResourceStatus;
}
