/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * Contact information for this resource.
 * @version 1.23.0
 */
export interface ResourceContactInfo {
    /**
     * Name of this contact.
     * @nullable
     */
    ContactName?: string | null;
    /**
     * Email address for this contact.
     * @nullable
     */
    EmailAddress?: string | null;
    /**
     * Phone number for this contact.
     * @nullable
     */
    PhoneNumber?: string | null;
}
