/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceContactInfo } from './ResourceContactInfo';
import type { ResourceOem } from './ResourceOem';
import type { ResourcePartLocation } from './ResourcePartLocation';
import type { ResourcePhysicalAddress } from './ResourcePhysicalAddress';
import type { ResourcePlacement } from './ResourcePlacement';
import type { ResourcePostalAddress } from './ResourcePostalAddress';

/**
 * The location of a resource.
 * @version 1.23.0
 */
export interface ResourceLocation {
    /**
     * The altitude of the resource in meters.
     * @nullable
     */
    AltitudeMeters?: number | null;
    /** An array of contact information. */
    Contacts?: ResourceContactInfo[];
    /**
     * The location of the resource.
     * @deprecated
     * @nullable
     */
    readonly Info?: string | null;
    /**
     * The format of the `Info` property.
     * @deprecated
     * @nullable
     */
    readonly InfoFormat?: string | null;
    /**
     * The latitude of the resource.
     * @nullable
     */
    Latitude?: number | null;
    /**
     * The longitude of the resource in degree units.
     * @nullable
     */
    Longitude?: number | null;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** The part location for a resource within an enclosure. */
    PartLocation?: ResourcePartLocation;
    /**
     * Human-readable string to enable differentiation between `PartLocation` values for parts in the same enclosure, which might include hierarchical information of containing `PartLocation` values for the part.
     * @nullable
     */
    readonly PartLocationContext?: string | null;
    /** The physical address for a resource. */
    PhysicalAddress?: ResourcePhysicalAddress;
    /** A place within the addressed location. */
    Placement?: ResourcePlacement;
    /** The postal address of the addressed resource. */
    PostalAddress?: ResourcePostalAddress;
}
