/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.0.1
 */
export type ResolutionStepResolutionType =
    (typeof ResolutionStepResolutionType)[keyof typeof ResolutionStepResolutionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResolutionStepResolutionType = {
    /** Contact vendor for service. */
    ContactVendor: 'ContactVendor',
    /** Replace a component. */
    ReplaceComponent: 'ReplaceComponent',
    /** Perform a firmware update operation. */
    FirmwareUpdate: 'FirmwareUpdate',
    /** Perform a reset operation. */
    Reset: 'Reset',
    /** Perform a power cycle operation. */
    PowerCycle: 'PowerCycle',
    /** Reset the settings to factory defaults. */
    ResetToDefaults: 'ResetToDefaults',
    /** Collect diagnostic data. */
    CollectDiagnosticData: 'CollectDiagnosticData',
    /** Perform an OEM-defined resolution step. */
    OEM: 'OEM',
} as const;
