/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The postal address for a resource.
 * @version 1.23.0
 * @deprecated
 */
export interface ResourcePostalAddress {
    /**
     * The additional code.
     * @nullable
     */
    AdditionalCode?: string | null;
    /**
     * The room designation or other additional information.
     * @nullable
     */
    AdditionalInfo?: string | null;
    /**
     * The name of the building.
     * @nullable
     */
    Building?: string | null;
    /**
     * City, township, or shi (JP).
     * @nullable
     */
    City?: string | null;
    /**
     * The postal community name.
     * @nullable
     */
    Community?: string | null;
    /**
     * The country.
     * @nullable
     */
    Country?: string | null;
    /**
     * A county, parish, gun (JP), or district (IN).
     * @nullable
     */
    District?: string | null;
    /**
     * City division, borough, city district, ward, or chou (JP).
     * @nullable
     */
    Division?: string | null;
    /**
     * The floor.
     * @nullable
     */
    Floor?: string | null;
    /**
     * The GPS coordinates of the part.
     * @deprecated
     * @nullable
     */
    GPSCoords?: string | null;
    /**
     * The numeric portion of house number.
     * @nullable
     */
    HouseNumber?: number | null;
    /**
     * The house number suffix.
     * @nullable
     */
    HouseNumberSuffix?: string | null;
    /**
     * The landmark.
     * @nullable
     */
    Landmark?: string | null;
    /**
     * A leading street direction.
     * @nullable
     */
    LeadingStreetDirection?: string | null;
    /**
     * The room designation or other additional information.
     * @deprecated
     * @nullable
     */
    Location?: string | null;
    /**
     * The name.
     * @nullable
     */
    Name?: string | null;
    /**
     * Neighborhood or block.
     * @nullable
     */
    Neighborhood?: string | null;
    /**
     * The post office box (PO box).
     * @nullable
     */
    POBox?: string | null;
    /**
     * The description of the type of place that is addressed.
     * @nullable
     */
    PlaceType?: string | null;
    /**
     * The postal code or zip code.
     * @nullable
     */
    PostalCode?: string | null;
    /**
     * The primary road or street.
     * @nullable
     */
    Road?: string | null;
    /**
     * The road branch.
     * @nullable
     */
    RoadBranch?: string | null;
    /**
     * The road post-modifier.
     * @nullable
     */
    RoadPostModifier?: string | null;
    /**
     * The road pre-modifier.
     * @nullable
     */
    RoadPreModifier?: string | null;
    /**
     * The road section.
     * @nullable
     */
    RoadSection?: string | null;
    /**
     * The road sub branch.
     * @nullable
     */
    RoadSubBranch?: string | null;
    /**
     * The name or number of the room.
     * @nullable
     */
    Room?: string | null;
    /**
     * The seat, such as the desk, cubicle, or workstation.
     * @nullable
     */
    Seat?: string | null;
    /**
     * Street name.
     * @nullable
     */
    Street?: string | null;
    /**
     * Avenue, Platz, Street, Circle.
     * @nullable
     */
    StreetSuffix?: string | null;
    /**
     * A top-level subdivision within a country.
     * @nullable
     */
    Territory?: string | null;
    /**
     * A trailing street suffix.
     * @nullable
     */
    TrailingStreetSuffix?: string | null;
    /**
     * The name or number of the apartment unit or suite.
     * @nullable
     */
    Unit?: string | null;
}
