/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The type of rack unit in use.
 * @version 1.23.0
 */
export type ResourceRackUnits =
    (typeof ResourceRackUnits)[keyof typeof ResourceRackUnits];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceRackUnits = {
    /** A rack unit that is equal to 48 mm (1.89 in). */
    OpenU: 'OpenU',
    /** A rack unit that is equal to 1.75 in (44.45 mm). */
    EIA_310: 'EIA_310',
} as const;
