/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

export type ResourceHealth =
    (typeof ResourceHealth)[keyof typeof ResourceHealth];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceHealth = {
    /** Normal. */
    OK: 'OK',
    /** A condition requires attention. */
    Warning: 'Warning',
    /** A critical condition requires immediate attention. */
    Critical: 'Critical',
} as const;
