/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.22.0
 */
export type ResourceConditionType =
    (typeof ResourceConditionType)[keyof typeof ResourceConditionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceConditionType = {
    /** The condition is an alert. */
    Alert: 'Alert',
    /** The condition is informational. */
    Informational: 'Informational',
    /** The condition is the health of a subsystem. */
    Subsystem: 'Subsystem',
} as const;
