/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The types of locations for a part within an enclosure.
 * @version 1.23.0
 */
export type ResourceLocationType =
    (typeof ResourceLocationType)[keyof typeof ResourceLocationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceLocationType = {
    /** A slot. */
    Slot: 'Slot',
    /** A bay. */
    Bay: 'Bay',
    /** A connector or port. */
    Connector: 'Connector',
    /** A socket. */
    Socket: 'Socket',
    /** A backplane. */
    Backplane: 'Backplane',
    /** Embedded within a part. */
    Embedded: 'Embedded',
} as const;
