/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceConditionType } from './ResourceConditionType';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { ResourceOem } from './ResourceOem';
import type { ResolutionStep } from './ResolutionStep';
import type { ResourceHealth } from './ResourceHealth';

/**
 * A condition that requires attention.
 */
export interface ResourceCondition {
    /**
     * The type of condition.
     * @nullable
     */
    readonly ConditionType?: ResourceConditionType;
    /** The link to the log entry created for this condition. */
    readonly LogEntry?: OdataV4IdRef;
    /** The human-readable message for this condition. */
    readonly Message?: string;
    /** An array of message arguments that are substituted for the arguments in the message when looked up in the message registry. */
    readonly MessageArgs?: readonly string[];
    /** The identifier for the message. */
    readonly MessageId: string;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** A link to the resource or object that originated the condition. */
    readonly OriginOfCondition?: OdataV4IdRef;
    /** Suggestions on how to resolve the condition. */
    readonly Resolution?: string;
    /** The list of recommended steps to resolve the condition. */
    ResolutionSteps?: ResolutionStep[];
    /** The severity of the condition. */
    readonly Severity?: ResourceHealth;
    /** The time the condition occurred. */
    readonly Timestamp?: string;
    /**
     * The source of authentication for the username property associated with the condition.
     * @nullable
     */
    readonly UserAuthenticationSource?: string | null;
    /**
     * The username of the account associated with the condition.
     * @nullable
     */
    readonly Username?: string | null;
}
