/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceRackUnits } from './ResourceRackUnits';

/**
 * The placement within the addressed location.
 * @version 1.23.0
 */
export interface ResourcePlacement {
    /**
     * Area designation or other additional info.
     * @nullable
     */
    AdditionalInfo?: string | null;
    /**
     * The name of the facility.
     * @nullable
     */
    FacilityName?: string | null;
    /**
     * The name of a rack location within a row.
     * @nullable
     */
    Rack?: string | null;
    /**
     * The vertical location of the item, in terms of RackOffsetUnits.
     * @nullable
     */
    RackOffset?: number | null;
    /**
     * The type of rack units in use.
     * @nullable
     */
    RackOffsetUnits?: ResourceRackUnits;
    /**
     * The name or number of the room.
     * @nullable
     */
    Room?: string | null;
    /**
     * The name of the row.
     * @nullable
     */
    Row?: string | null;
}
