/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceLocationType } from './ResourceLocationType';
import type { ResourceOrientation } from './ResourceOrientation';
import type { ResourceReference } from './ResourceReference';

/**
 * The part location for a resource within an enclosure.
 * @version 1.23.0
 */
export interface ResourcePartLocation {
    /**
     * The number that represents the location of the part.  For example, if `LocationType` is `Slot` and this unit is in slot 2, the LocationOrdinalValue is `2`.
     * @nullable
     */
    readonly LocationOrdinalValue?: number | null;
    /**
     * The type of location of the part.
     * @nullable
     */
    readonly LocationType?: ResourceLocationType;
    /**
     * The orientation for the ordering of the slot enumeration used by the `LocationOrdinalValue` property.
     * @nullable
     */
    readonly Orientation?: ResourceOrientation;
    /**
     * The reference point for the part location.  Provides guidance about the general location of the part.
     * @nullable
     */
    readonly Reference?: ResourceReference;
    /**
     * The label of the part location, such as a silk-screened name or a printed label.
     * @nullable
     */
    readonly ServiceLabel?: string | null;
}
