/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The orientations for the ordering of the part location ordinal value.
 * @version 1.23.0
 */
export type ResourceOrientation =
    (typeof ResourceOrientation)[keyof typeof ResourceOrientation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceOrientation = {
    /** The ordering for `LocationOrdinalValue` is front to back. */
    FrontToBack: 'FrontToBack',
    /** The ordering for the LocationOrdinalValue is back to front. */
    BackToFront: 'BackToFront',
    /** The ordering for the LocationOrdinalValue is top to bottom. */
    TopToBottom: 'TopToBottom',
    /** The ordering for `LocationOrdinalValue` is bottom to top. */
    BottomToTop: 'BottomToTop',
    /** The ordering for the LocationOrdinalValue is left to right. */
    LeftToRight: 'LeftToRight',
    /** The ordering for the LocationOrdinalValue is right to left. */
    RightToLeft: 'RightToLeft',
} as const;
