/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The description of this resource.  Used for commonality in the schema definitions.
 */
export type ResourceDescription = string;
