/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceCondition } from './ResourceCondition';
import type { ResourceHealth } from './ResourceHealth';
import type { ResourceOem } from './ResourceOem';
import type { ResourceState } from './ResourceState';

/**
 * The status and health of a resource and its children.
 */
export interface ResourceStatus {
    /** Conditions in this resource that require attention. */
    Conditions?: ResourceCondition[];
    /**
     * The health state of this resource in the absence of its dependent resources.
     * @nullable
     */
    readonly Health?: ResourceHealth;
    /**
     * The overall health state from the view of this resource.
     * @nullable
     */
    readonly HealthRollup?: ResourceHealth;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The state of the resource.
     * @nullable
     */
    readonly State?: ResourceState;
}
