/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

export type ResourceState = (typeof ResourceState)[keyof typeof ResourceState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceState = {
    /** This function or resource is enabled. */
    Enabled: 'Enabled',
    /** This function or resource is disabled. */
    Disabled: 'Disabled',
    /** This function or resource is enabled but awaits an external action to activate it. */
    StandbyOffline: 'StandbyOffline',
    /** This function or resource is part of a redundancy set and awaits a failover or other external action to activate it. */
    StandbySpare: 'StandbySpare',
    /** This function or resource is undergoing testing or is in the process of capturing information for debugging. */
    InTest: 'InTest',
    /** This function or resource is starting. */
    Starting: 'Starting',
    /** This function or device is not currently present or detected.  This resource represents a capability or an available location where a device can be installed. */
    Absent: 'Absent',
    /** This function or resource is present but cannot be used. */
    UnavailableOffline: 'UnavailableOffline',
    /** The element does not process any commands but queues new requests. */
    Deferring: 'Deferring',
    /** The element is enabled but only processes a restricted set of commands. */
    Quiesced: 'Quiesced',
    /** The element is updating and might be unavailable or degraded. */
    Updating: 'Updating',
    /** The element quality is within the acceptable range of operation. */
    Qualified: 'Qualified',
    /** The function or resource is degraded. */
    Degraded: 'Degraded',
} as const;
