/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The physical address for a resource.
 * @version 1.23.0
 */
export interface ResourcePhysicalAddress {
    /**
     * City, township, or shi (JP).
     * @nullable
     */
    City?: string | null;
    /**
     * The country.
     * @nullable
     */
    Country?: string | null;
    /**
     * The ISO 3166-1 country code.
     * @nullable
     * @pattern ^([A-Z]{2}|[A-Z]{3})$
     */
    ISOCountryCode?: string | null;
    /**
     * ISO 3166-2 subdivision code.
     * @nullable
     * @pattern ^[A-Z0-9]{1,3}$
     */
    ISOSubdivisionCode?: string | null;
    /**
     * The postal code.
     * @nullable
     */
    PostalCode?: string | null;
    /**
     * State or province.
     * @nullable
     */
    StateOrProvince?: string | null;
    /**
     * The street-level address, including building, room, or other identifiers.
     * @nullable
     */
    StreetAddress?: string | null;
}
