/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The reference areas for the location of the part within an enclosure.
 * @version 1.23.0
 */
export type ResourceReference =
    (typeof ResourceReference)[keyof typeof ResourceReference];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceReference = {
    /** The part is in the top of the unit. */
    Top: 'Top',
    /** The part is in the bottom of the unit. */
    Bottom: 'Bottom',
    /** The part is in the front of the unit. */
    Front: 'Front',
    /** The part is in the rear of the unit. */
    Rear: 'Rear',
    /** The part is on the left side of the unit. */
    Left: 'Left',
    /** The part is on the right side of the unit. */
    Right: 'Right',
    /** The part is in the middle of the unit. */
    Middle: 'Middle',
} as const;
