/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ActionInfoParameters } from './ActionInfoParameters';
import type { ResourceOem } from './ResourceOem';
import type { ResolutionStepResolutionType } from './ResolutionStepResolutionType';

/**
 * This type describes a recommended step of the service-defined resolution.
 * @version 1.0.1
 */
export interface ResolutionStep {
    /** The parameters of the action URI for a resolution step. */
    ActionParameters?: ActionInfoParameters[];
    /** The action URI for a resolution step. */
    readonly ActionURI?: string;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The priority in the set of resolution steps.
     * @minimum 0
     * @nullable
     */
    readonly Priority?: number | null;
    /**
     * The type of the resolution step.
     * @nullable
     */
    readonly ResolutionType: ResolutionStepResolutionType;
    /**
     * The number of retries for a resolution step.
     * @minimum 0
     * @nullable
     */
    readonly RetryCount?: number | null;
    /**
     * The interval between retries for a resolution step.
     * @minimum 0
     * @nullable
     */
    readonly RetryIntervalSeconds?: number | null;
    /**
     * The target URI of the component for a resolution step.
     * @nullable
     */
    readonly TargetComponentURI?: string | null;
}
