/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { RoleActions } from './RoleActions';
import type { PrivilegesPrivilegeType } from './PrivilegesPrivilegeType';
import type { ResourceDescription } from './ResourceDescription';
import type { ResourceId } from './ResourceId';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';

/**
 * The `Role` schema contains a Redfish role to use in conjunction with a manager account.
 * @version 1.3.3
 */
export interface Role {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /** The available actions for this resource. */
    Actions?: RoleActions;
    /** An equivalent role to use when this role is restricted. */
    readonly AlternateRoleId?: string;
    /** The Redfish privileges for this role. */
    AssignedPrivileges?: PrivilegesPrivilegeType[];
    /** @nullable */
    readonly Description?: ResourceDescription;
    readonly Id: ResourceId;
    /** An indication of whether the role is predefined by Redfish or an OEM rather than a client-defined role. */
    readonly IsPredefined?: boolean;
    readonly Name: ResourceName;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** The OEM privileges for this role. */
    OemPrivileges?: string[];
    /** An indication of whether use of the role is restricted. */
    readonly Restricted?: boolean;
    /** The name of the role. */
    readonly RoleId: string;
}
