/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

export type SensorElectricalContext =
    (typeof SensorElectricalContext)[keyof typeof SensorElectricalContext];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SensorElectricalContext = {
    /** The circuits that share the L1 current-carrying conductor. */
    Line1: 'Line1',
    /** The circuits that share the L2 current-carrying conductor. */
    Line2: 'Line2',
    /** The circuits that share the L3 current-carrying conductor. */
    Line3: 'Line3',
    /** The grounded current-carrying return circuit of current-carrying conductors. */
    Neutral: 'Neutral',
    /** The circuit formed by two current-carrying conductors. */
    LineToLine: 'LineToLine',
    /** The circuit formed by L1 and L2 current-carrying conductors. */
    Line1ToLine2: 'Line1ToLine2',
    /** The circuit formed by L2 and L3 current-carrying conductors. */
    Line2ToLine3: 'Line2ToLine3',
    /** The circuit formed by L3 and L1 current-carrying conductors. */
    Line3ToLine1: 'Line3ToLine1',
    /** The circuit formed by a line and neutral current-carrying conductor. */
    LineToNeutral: 'LineToNeutral',
    /** The circuit formed by L1 and neutral current-carrying conductors. */
    Line1ToNeutral: 'Line1ToNeutral',
    /** The circuit formed by L2 and neutral current-carrying conductors. */
    Line2ToNeutral: 'Line2ToNeutral',
    /** The circuit formed by L3 and neutral current-carrying conductors. */
    Line3ToNeutral: 'Line3ToNeutral',
    /** The circuit formed by L1, L2, and neutral current-carrying conductors. */
    Line1ToNeutralAndL1L2: 'Line1ToNeutralAndL1L2',
    /** The circuit formed by L1, L2, and Neutral current-carrying conductors. */
    Line2ToNeutralAndL1L2: 'Line2ToNeutralAndL1L2',
    /** The circuits formed by L2, L3, and neutral current-carrying conductors. */
    Line2ToNeutralAndL2L3: 'Line2ToNeutralAndL2L3',
    /** The circuit formed by L3, L1, and neutral current-carrying conductors. */
    Line3ToNeutralAndL3L1: 'Line3ToNeutralAndL3L1',
    /** The circuit formed by all current-carrying conductors. */
    Total: 'Total',
} as const;
