/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.12.0
 */
export type SensorReadingType =
    (typeof SensorReadingType)[keyof typeof SensorReadingType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SensorReadingType = {
    /** Temperature (C). */
    Temperature: 'Temperature',
    /** Relative humidity (percent). */
    Humidity: 'Humidity',
    /** Power (W). */
    Power: 'Power',
    /** Energy (kWh). */
    EnergykWh: 'EnergykWh',
    /** Energy (J). */
    EnergyJoules: 'EnergyJoules',
    /** Energy (Wh). */
    EnergyWh: 'EnergyWh',
    /** Charge (Ah). */
    ChargeAh: 'ChargeAh',
    /** Voltage (VAC or VDC). */
    Voltage: 'Voltage',
    /** Current (A). */
    Current: 'Current',
    /** Frequency (Hz). */
    Frequency: 'Frequency',
    /** Pressure (Pa). */
    Pressure: 'Pressure',
    /** Pressure (kPa). */
    PressurekPa: 'PressurekPa',
    /** Pressure (Pa). */
    PressurePa: 'PressurePa',
    /** Liquid level (cm). */
    LiquidLevel: 'LiquidLevel',
    /** Rotational (RPM). */
    Rotational: 'Rotational',
    /** Air flow (cu ft/min). */
    AirFlow: 'AirFlow',
    /** Air flow (m^3/min). */
    AirFlowCMM: 'AirFlowCMM',
    /** Liquid flow (L/s). */
    LiquidFlow: 'LiquidFlow',
    /** Liquid flow (L/min). */
    LiquidFlowLPM: 'LiquidFlowLPM',
    /** Barometric pressure (mm). */
    Barometric: 'Barometric',
    /** Altitude (m). */
    Altitude: 'Altitude',
    /** Percent (%). */
    Percent: 'Percent',
    /** Absolute humidity (g/m^3). */
    AbsoluteHumidity: 'AbsoluteHumidity',
    /** Heat (kW). */
    Heat: 'Heat',
    /** Linear position or distance (m). */
    LinearPosition: 'LinearPosition',
    /** Linear velocity (m/s). */
    LinearVelocity: 'LinearVelocity',
    /** Linear acceleration (m/s^2). */
    LinearAcceleration: 'LinearAcceleration',
    /** Rotational position (rad). */
    RotationalPosition: 'RotationalPosition',
    /** Rotational velocity (rad/s). */
    RotationalVelocity: 'RotationalVelocity',
    /** Rotational acceleration (rad/s^2). */
    RotationalAcceleration: 'RotationalAcceleration',
    /** Valve (% open). */
    Valve: 'Valve',
} as const;
