/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { SensorActions } from './SensorActions';
import type { ResourceDescription } from './ResourceDescription';
import type { SensorElectricalContext } from './SensorElectricalContext';
import type { ResourceId } from './ResourceId';
import type { SensorImplementationType } from './SensorImplementationType';
import type { SensorLinks } from './SensorLinks';
import type { ResourceLocation } from './ResourceLocation';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';
import type { PhysicalContext } from './PhysicalContext';
import type { PhysicalContextPhysicalSubContext } from './PhysicalContextPhysicalSubContext';
import type { SensorReadingBasisType } from './SensorReadingBasisType';
import type { SensorReadingType } from './SensorReadingType';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { OdataV4Count } from './OdataV4Count';
import type { RedundancyRedundantGroup } from './RedundancyRedundantGroup';
import type { ResourceStatus } from './ResourceStatus';
import type { SensorThresholds } from './SensorThresholds';
import type { SensorVoltageType } from './SensorVoltageType';

/**
 * The `Sensor` schema describes a sensor and its properties.
 * @version 1.12.0
 */
export interface Sensor {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /**
     * The estimated percent error of measured versus actual values.
     * @deprecated
     * @nullable
     */
    readonly Accuracy?: number | null;
    /** The available actions for this resource. */
    Actions?: SensorActions;
    /**
     * The adjusted maximum allowable operating value for this equipment based on the environmental conditions.
     * @nullable
     */
    readonly AdjustedMaxAllowableOperatingValue?: number | null;
    /**
     * The adjusted minimum allowable operating value for this equipment based on the environmental conditions.
     * @nullable
     */
    readonly AdjustedMinAllowableOperatingValue?: number | null;
    /**
     * The product of voltage and current for an AC circuit, in volt-ampere units.
     * @nullable
     */
    readonly ApparentVA?: number | null;
    /**
     * Apparent energy (kVAh).
     * @nullable
     */
    readonly ApparentkVAh?: number | null;
    /**
     * The average sensor value.
     * @nullable
     */
    readonly AverageReading?: number | null;
    /**
     * The interval over which the average sensor value is calculated.
     * @nullable
     * @pattern ^P(\d+D)?(T(\d+H)?(\d+M)?(\d+(.\d+)?S)?)?$
     */
    AveragingInterval?: string | null;
    /**
     * Indicates that enough readings were collected to calculate the average sensor reading over the averaging interval time.
     * @nullable
     */
    readonly AveragingIntervalAchieved?: boolean | null;
    /**
     * The calibration offset applied to the Reading.
     * @nullable
     */
    Calibration?: number | null;
    /**
     * The date and time that the sensor was last calibrated.
     * @nullable
     */
    CalibrationTime?: string | null;
    /**
     * The crest factor for this sensor.
     * @nullable
     */
    readonly CrestFactor?: number | null;
    /** @nullable */
    readonly Description?: ResourceDescription;
    /**
     * The combination of current-carrying conductors.
     * @nullable
     */
    readonly ElectricalContext?: SensorElectricalContext;
    /**
     * Indicates whether the sensor is enabled and provides a reading.
     * @nullable
     */
    Enabled?: boolean | null;
    readonly Id: ResourceId;
    /**
     * The implementation of the sensor.
     * @nullable
     */
    readonly Implementation?: SensorImplementationType;
    /**
     * The total accumulation value for this sensor.
     * @nullable
     */
    readonly LifetimeReading?: number | null;
    /**
     * The date and time when the sensor started accumulating readings for the `LifetimeReading` property.
     * @nullable
     */
    readonly LifetimeStartDateTime?: string | null;
    /** The links to other resources that are related to this resource. */
    Links?: SensorLinks;
    /**
     * The power load utilization for this sensor.
     * @deprecated
     * @nullable
     */
    readonly LoadPercent?: number | null;
    /** The location information for this sensor. */
    Location?: ResourceLocation;
    /**
     * The lowest sensor value over a time interval.
     * @nullable
     */
    readonly LowestIntervalReading?: number | null;
    /**
     * The lowest sensor value.
     * @nullable
     */
    readonly LowestReading?: number | null;
    /**
     * The time when the lowest sensor value occurred.
     * @nullable
     */
    readonly LowestReadingTime?: string | null;
    /**
     * The manufacturer of this sensor.
     * @nullable
     */
    readonly Manufacturer?: string | null;
    /**
     * The maximum allowable operating value for this equipment.
     * @nullable
     */
    readonly MaxAllowableOperatingValue?: number | null;
    /**
     * The minimum allowable operating value for this equipment.
     * @nullable
     */
    readonly MinAllowableOperatingValue?: number | null;
    /**
     * The model number of the sensor.
     * @nullable
     */
    readonly Model?: string | null;
    readonly Name: ResourceName;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The part number of the sensor.
     * @nullable
     */
    readonly PartNumber?: string | null;
    /**
     * The peak sensor value over a time interval.
     * @nullable
     */
    readonly PeakIntervalReading?: number | null;
    /**
     * The peak sensor value.
     * @nullable
     */
    readonly PeakReading?: number | null;
    /**
     * The time when the peak sensor value occurred.
     * @nullable
     */
    readonly PeakReadingTime?: string | null;
    /**
     * The phase angle (degrees) between the current and voltage waveforms.
     * @minimum -90
     * @maximum 90
     * @nullable
     */
    readonly PhaseAngleDegrees?: number | null;
    /**
     * The area or device to which this sensor measurement applies.
     * @nullable
     */
    PhysicalContext?: PhysicalContext;
    /**
     * The usage or location within a device to which this sensor measurement applies.
     * @nullable
     */
    PhysicalSubContext?: PhysicalContextPhysicalSubContext;
    /**
     * The power factor for this sensor.
     * @minimum -1
     * @maximum 1
     * @nullable
     */
    readonly PowerFactor?: number | null;
    /**
     * The number of significant digits in the reading.
     * @nullable
     */
    readonly Precision?: number | null;
    /**
     * The square root of the difference term of squared apparent VA and squared power (Reading) for a circuit, in VAR units.
     * @nullable
     */
    readonly ReactiveVAR?: number | null;
    /**
     * Reactive energy (kVARh).
     * @nullable
     */
    readonly ReactivekVARh?: number | null;
    /**
     * The sensor value.
     * @nullable
     */
    readonly Reading?: number | null;
    /**
     * Accuracy (+/-) of the reading.
     * @nullable
     */
    readonly ReadingAccuracy?: number | null;
    /**
     * The basis for the reading of this sensor.
     * @nullable
     */
    readonly ReadingBasis?: SensorReadingBasisType;
    /**
     * The maximum possible value for this sensor.
     * @nullable
     */
    readonly ReadingRangeMax?: number | null;
    /**
     * The minimum possible value for this sensor.
     * @nullable
     */
    readonly ReadingRangeMin?: number | null;
    /**
     * The date and time that the reading was acquired from the sensor.
     * @nullable
     */
    readonly ReadingTime?: string | null;
    /**
     * The type of sensor.
     * @nullable
     */
    readonly ReadingType?: SensorReadingType;
    /**
     * The units of the reading, thresholds, and other reading-related properties in UCUM c/s format.
     * @nullable
     */
    readonly ReadingUnits?: string | null;
    /** An array of links to resources or objects that this sensor services. */
    RelatedItem?: OdataV4IdRef[];
    'RelatedItem@odata.count'?: OdataV4Count;
    /**
     * The SKU of the sensor.
     * @nullable
     */
    readonly SKU?: string | null;
    /**
     * The time interval between readings of the physical sensor.
     * @deprecated
     * @nullable
     */
    readonly SensingFrequency?: number | null;
    /**
     * The time interval between readings of the sensor.
     * @nullable
     * @pattern ^P(\d+D)?(T(\d+H)?(\d+M)?(\d+(.\d+)?S)?)?$
     */
    readonly SensingInterval?: string | null;
    /** The group of sensors that provide readings for this sensor. */
    SensorGroup?: RedundancyRedundantGroup;
    /**
     * The date and time when the time-based properties were last reset.
     * @nullable
     */
    readonly SensorResetTime?: string | null;
    /**
     * The serial number of the sensor.
     * @nullable
     */
    readonly SerialNumber?: string | null;
    /**
     * The spare part number of the sensor.
     * @nullable
     */
    readonly SparePartNumber?: string | null;
    /**
     * The rotational speed.
     * @nullable
     */
    readonly SpeedRPM?: number | null;
    /** The status and health of the resource and its subordinate or dependent resources. */
    Status?: ResourceStatus;
    /**
     * The total harmonic distortion percent (% THD).
     * @minimum 0
     * @nullable
     */
    readonly THDPercent?: number | null;
    /** The set of thresholds defined for this sensor. */
    Thresholds?: SensorThresholds;
    /** A user-assigned label. */
    UserLabel?: string;
    /**
     * The voltage type for this sensor.
     * @nullable
     */
    readonly VoltageType?: SensorVoltageType;
}
