/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.12.0
 */
export type SensorReadingBasisType =
    (typeof SensorReadingBasisType)[keyof typeof SensorReadingBasisType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SensorReadingBasisType = {
    /** A zero-based reading. */
    Zero: 'Zero',
    /** A reading that reports the difference between two measurements. */
    Delta: 'Delta',
    /** A reading that decreases as it approaches a defined reference point. */
    Headroom: 'Headroom',
} as const;
