/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * Resets metrics related to this sensor.
 * @version 1.12.0
 */
export interface SensorResetMetrics {
    /** Link to invoke action */
    target?: string;
    /** Friendly action name */
    title?: string;
}
