/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

export type SensorVoltageType =
    (typeof SensorVoltageType)[keyof typeof SensorVoltageType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SensorVoltageType = {
    /** Alternating current. */
    AC: 'AC',
    /** Direct current. */
    DC: 'DC',
} as const;
