/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { SensorThresholdActivation } from './SensorThresholdActivation';

/**
 * The threshold definition for a sensor.
 * @version 1.12.0
 */
export interface SensorThreshold {
    /**
     * The direction of crossing that activates this threshold.
     * @nullable
     */
    Activation?: SensorThresholdActivation;
    /**
     * The duration the sensor value must violate the threshold before the threshold is activated.
     * @nullable
     * @pattern ^P(\d+D)?(T(\d+H)?(\d+M)?(\d+(.\d+)?S)?)?$
     */
    DwellTime?: string | null;
    /**
     * The duration the sensor value must not violate the threshold before the threshold is deactivated.
     * @nullable
     * @pattern ^P(\d+D)?(T(\d+H)?(\d+M)?(\d+(.\d+)?S)?)?$
     */
    HysteresisDuration?: string | null;
    /**
     * The reading offset from the threshold value required to clear the threshold.
     * @nullable
     */
    HysteresisReading?: number | null;
    /**
     * The threshold value.
     * @nullable
     */
    Reading?: number | null;
}
