/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.12.0
 */
export type SensorImplementationType =
    (typeof SensorImplementationType)[keyof typeof SensorImplementationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SensorImplementationType = {
    /** The reading is acquired from a physical sensor. */
    PhysicalSensor: 'PhysicalSensor',
    /** The reading is obtained by applying a calculation on one or more properties or multiple sensors.  The calculation is not provided. */
    Synthesized: 'Synthesized',
    /** The reading is obtained from software or a device. */
    Reported: 'Reported',
} as const;
