/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.12.0
 */
export type SensorThresholdActivation =
    (typeof SensorThresholdActivation)[keyof typeof SensorThresholdActivation];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SensorThresholdActivation = {
    /** Value increases above the threshold. */
    Increasing: 'Increasing',
    /** Value decreases below the threshold. */
    Decreasing: 'Decreasing',
    /** Value crosses the threshold in either direction. */
    Either: 'Either',
    /** The threshold is disabled. */
    Disabled: 'Disabled',
} as const;
