/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { SensorResetMetrics } from './SensorResetMetrics';
import type { SensorResetToDefaults } from './SensorResetToDefaults';
import type { SensorOemActions } from './SensorOemActions';

/**
 * The available actions for this resource.
 * @version 1.12.0
 */
export interface SensorActions {
    '#Sensor.ResetMetrics'?: SensorResetMetrics;
    '#Sensor.ResetToDefaults'?: SensorResetToDefaults;
    /** The available OEM-specific actions for this resource. */
    Oem?: SensorOemActions;
}
