/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { SensorThreshold } from './SensorThreshold';

/**
 * The set of thresholds defined for a sensor.
 * @version 1.12.0
 */
export interface SensorThresholds {
    /** The value at which the reading is below normal range. */
    LowerCaution?: SensorThreshold;
    /** A user-defined value at which the reading is considered below normal range. */
    LowerCautionUser?: SensorThreshold;
    /** The value at which the reading is below normal range but not yet fatal. */
    LowerCritical?: SensorThreshold;
    /** A user-defined value at which the reading is considered below normal range but not yet fatal. */
    LowerCriticalUser?: SensorThreshold;
    /** The value at which the reading is below normal range and fatal. */
    LowerFatal?: SensorThreshold;
    /** The value at which the reading is above normal range. */
    UpperCaution?: SensorThreshold;
    /** A user-defined value at which the reading is considered above normal range. */
    UpperCautionUser?: SensorThreshold;
    /** The value at which the reading is above normal range but not yet fatal. */
    UpperCritical?: SensorThreshold;
    /** A user-defined value at which the reading is considered above normal range but not yet fatal. */
    UpperCriticalUser?: SensorThreshold;
    /** The value at which the reading is above normal range and fatal. */
    UpperFatal?: SensorThreshold;
}
