/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { ResourceDescription } from './ResourceDescription';
import type { ResourceId } from './ResourceId';
import type { ServiceRootLinks } from './ServiceRootLinks';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';
import type { ServiceRootProtocolFeaturesSupported } from './ServiceRootProtocolFeaturesSupported';

/**
 * The `ServiceRoot` schema describes the root of the Redfish service, located at the '/redfish/v1' URI.  All other resources accessible through the Redfish interface on this device are linked directly or indirectly from the service root.
 * @version 1.20.0
 */
export interface ServiceRoot {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /** The link to the account service. */
    readonly AccountService?: OdataV4IdRef;
    /** The link to the aggregation service. */
    readonly AggregationService?: OdataV4IdRef;
    /** The link to a collection of automation nodes. */
    readonly AutomationNodes?: OdataV4IdRef;
    /** The link to a collection of cables. */
    readonly Cables?: OdataV4IdRef;
    /** The link to the certificate service. */
    readonly CertificateService?: OdataV4IdRef;
    /** The link to a collection of chassis. */
    readonly Chassis?: OdataV4IdRef;
    /** The link to a collection of component integrity information. */
    readonly ComponentIntegrity?: OdataV4IdRef;
    /** The link to the composition service. */
    readonly CompositionService?: OdataV4IdRef;
    /** @nullable */
    readonly Description?: ResourceDescription;
    /** The link to the event service. */
    readonly EventService?: OdataV4IdRef;
    /** The link to a collection of fabrics. */
    readonly Fabrics?: OdataV4IdRef;
    /** The link to a collection of facilities. */
    readonly Facilities?: OdataV4IdRef;
    readonly Id: ResourceId;
    /** The link to the job service. */
    readonly JobService?: OdataV4IdRef;
    /** The link to a collection of JSON Schema files. */
    readonly JsonSchemas?: OdataV4IdRef;
    /** The link to the key service. */
    readonly KeyService?: OdataV4IdRef;
    /** The link to the license service. */
    readonly LicenseService?: OdataV4IdRef;
    /** The links to other resources that are related to this resource. */
    Links: ServiceRootLinks;
    /** The link to a collection of managers. */
    readonly Managers?: OdataV4IdRef;
    /** The link to a collection of NVMe domains. */
    readonly NVMeDomains?: OdataV4IdRef;
    readonly Name: ResourceName;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** The link to a set of power equipment. */
    readonly PowerEquipment?: OdataV4IdRef;
    /**
     * The product associated with this Redfish service.
     * @nullable
     */
    readonly Product?: string | null;
    /** The information about protocol features that the service supports. */
    ProtocolFeaturesSupported?: ServiceRootProtocolFeaturesSupported;
    /**
     * The version of the Redfish service.
     * @pattern ^\d+\.\d+\.\d+$
     */
    readonly RedfishVersion?: string;
    /** The link to a collection of registered clients. */
    readonly RegisteredClients?: OdataV4IdRef;
    /** The link to a collection of registries. */
    readonly Registries?: OdataV4IdRef;
    /** The link to a collection of resource blocks.  This collection is intended for implementations that do not contain a composition service but that expose resources to an orchestrator that implements a composition service. */
    readonly ResourceBlocks?: OdataV4IdRef;
    /** The link to the service conditions. */
    readonly ServiceConditions?: OdataV4IdRef;
    /** The vendor or user-provided product and service identifier. */
    readonly ServiceIdentification?: string;
    /** The usage notification message for this service. */
    readonly ServiceUseNotification?: string;
    /** The link to the sessions service. */
    readonly SessionService?: OdataV4IdRef;
    /** The link to a collection of storage subsystems. */
    readonly Storage?: OdataV4IdRef;
    /** The link to a collection of storage services. */
    readonly StorageServices?: OdataV4IdRef;
    /** The link to a collection of storage systems. */
    readonly StorageSystems?: OdataV4IdRef;
    /** The link to a collection of systems. */
    readonly Systems?: OdataV4IdRef;
    /** The link to the task service. */
    readonly Tasks?: OdataV4IdRef;
    /** The link to the telemetry service. */
    readonly TelemetryService?: OdataV4IdRef;
    /** The link to a set of cooling equipment. */
    readonly ThermalEquipment?: OdataV4IdRef;
    /**
     * Unique identifier for a service instance.  When SSDP is used, this value contains the same UUID returned in an HTTP `200 OK` response from an SSDP `M-SEARCH` request during discovery.
     * @nullable
     * @pattern ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
     */
    readonly UUID?: string | null;
    /** The link to the update service. */
    readonly UpdateService?: OdataV4IdRef;
    /**
     * The vendor or manufacturer associated with this Redfish service.
     * @nullable
     */
    readonly Vendor?: string | null;
}
