/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The information about deep operations that the service supports.
 * @version 1.20.0
 */
export interface ServiceRootDeepOperations {
    /** An indication of whether the service supports the deep `PATCH` operation. */
    readonly DeepPATCH?: boolean;
    /** An indication of whether the service supports the deep `POST` operation. */
    readonly DeepPOST?: boolean;
    /**
     * The maximum levels of resources allowed in deep operations.
     * @minimum 1
     */
    readonly MaxLevels?: number;
}
