/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The information about the use of `$expand` in the service.
 * @version 1.20.0
 */
export interface ServiceRootExpand {
    /** An indication of whether the service supports the asterisk (`*`) option of the `$expand` query parameter. */
    readonly ExpandAll?: boolean;
    /** An indication of whether the service supports the `$levels` option of the `$expand` query parameter. */
    readonly Levels?: boolean;
    /** An indication of whether this service supports the tilde (`~`) option of the `$expand` query parameter. */
    readonly Links?: boolean;
    /**
     * The maximum `$levels` option value in the `$expand` query parameter.
     * @minimum 1
     */
    readonly MaxLevels?: number;
    /** An indication of whether the service supports the period (`.`) option of the `$expand` query parameter. */
    readonly NoLinks?: boolean;
}
