/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ServiceRootDeepOperations } from './ServiceRootDeepOperations';
import type { ServiceRootExpand } from './ServiceRootExpand';

/**
 * The information about protocol features that the service supports.
 * @version 1.20.0
 */
export interface ServiceRootProtocolFeaturesSupported {
    /** The information about deep operations that the service supports. */
    DeepOperations?: ServiceRootDeepOperations;
    /** An indication of whether the service supports the `excerpt` query parameter. */
    readonly ExcerptQuery?: boolean;
    /** The information about the use of `$expand` in the service. */
    ExpandQuery?: ServiceRootExpand;
    /** An indication of whether the service supports the `$filter` query parameter. */
    readonly FilterQuery?: boolean;
    /** An indication of whether the service supports the `eq`, `ge`, `gt`, `le`, `lt`, and `ne` options for the `$filter` query parameter. */
    readonly FilterQueryComparisonOperations?: boolean;
    /** An indication of whether the service supports the `()`, `and`, `not`, and `or` options for the `$filter` query parameter. */
    readonly FilterQueryCompoundOperations?: boolean;
    /** An indication of whether the service supports the `includeoriginofcondition` query parameter. */
    readonly IncludeOriginOfConditionQuery?: boolean;
    /** An indication of whether the service supports multiple outstanding HTTP requests. */
    readonly MultipleHTTPRequests?: boolean;
    /** An indication of whether the service supports the `only` query parameter. */
    readonly OnlyMemberQuery?: boolean;
    /** An indication of whether the service supports the `$select` query parameter. */
    readonly SelectQuery?: boolean;
    /** An indication of whether the service supports both the `$top` and `$skip` query parameters. */
    readonly TopSkipQuery?: boolean;
}
