/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { ResourceOem } from './ResourceOem';

/**
 * The links to other resources that are related to this resource.
 * @version 1.20.0
 */
export interface ServiceRootLinks {
    /** The link to the manager that is providing this Redfish service. */
    readonly ManagerProvidingService?: OdataV4IdRef;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** The link to a collection of sessions. */
    readonly Sessions: OdataV4IdRef;
}
