/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceOem } from './ResourceOem';
import type { OdataV4IdRef } from './OdataV4IdRef';

/**
 * The links to other resources that are related to this resource.
 * @version 1.8.0
 */
export interface SessionLinks {
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** The outbound connection associated with this session. */
    readonly OutboundConnection?: OdataV4IdRef;
}
