/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { SessionActions } from './SessionActions';
import type { ResourceDescription } from './ResourceDescription';
import type { ResourceId } from './ResourceId';
import type { SessionLinks } from './SessionLinks';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';
import type { SessionTypes } from './SessionTypes';

/**
 * The `Session` resource describes a single connection (session) between a client and a Redfish service instance.
 * @version 1.8.0
 */
export interface Session {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /** The available actions for this resource. */
    Actions?: SessionActions;
    /**
     * The IP address of the client that created the session.
     * @nullable
     */
    readonly ClientOriginIPAddress?: string | null;
    /**
     * A client-supplied string that is stored with the session.
     * @nullable
     */
    readonly Context?: string | null;
    /**
     * The date and time when the session was created.
     * @nullable
     */
    readonly CreatedTime?: string | null;
    /** @nullable */
    readonly Description?: ResourceDescription;
    /** The date and time when the session expires regardless of session activity. */
    readonly ExpirationTime?: string;
    readonly Id: ResourceId;
    /** The links to other resources that are related to this resource. */
    Links?: SessionLinks;
    readonly Name: ResourceName;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /**
     * The active OEM-defined session type.
     * @nullable
     */
    readonly OemSessionType?: string | null;
    /**
     * The password for this session.  The value is `null` in responses.
     * @nullable
     */
    readonly Password?: string | null;
    /** The Redfish roles that contain the privileges of this session. */
    readonly Roles?: readonly (string | null)[];
    /**
     * The active session type.
     * @nullable
     */
    readonly SessionType?: SessionTypes;
    /**
     * The multi-factor authentication token for this session.  The value is `null` in responses.
     * @nullable
     */
    readonly Token?: string | null;
    /**
     * The username for the account for this session.
     * @nullable
     */
    readonly UserName?: string | null;
}
