/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.8.0
 */
export type SessionTypes = (typeof SessionTypes)[keyof typeof SessionTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SessionTypes = {
    /** The host\'s console, which could be connected through Telnet, SSH, or another protocol. */
    HostConsole: 'HostConsole',
    /** The manager\'s console, which could be connected through Telnet, SSH, SM CLP, or another protocol. */
    ManagerConsole: 'ManagerConsole',
    /** Intelligent Platform Management Interface. */
    IPMI: 'IPMI',
    /** A Keyboard-Video-Mouse over IP session. */
    KVMIP: 'KVMIP',
    /** OEM type.  For OEM session types, see the `OemSessionType` property. */
    OEM: 'OEM',
    /** A Redfish session. */
    Redfish: 'Redfish',
    /** Virtual media. */
    VirtualMedia: 'VirtualMedia',
    /** A non-Redfish web user interface session, such as a graphical interface or another web-based protocol. */
    WebUI: 'WebUI',
    /** A Redfish Specification-defined outbound connection.  See the \'Outbound connections\' clause of the Redfish Specification. */
    OutboundConnection: 'OutboundConnection',
} as const;
