/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { SessionOemActions } from './SessionOemActions';

/**
 * The available actions for this resource.
 * @version 1.8.0
 */
export interface SessionActions {
    /** The available OEM-specific actions for this resource. */
    Oem?: SessionOemActions;
}
