/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { OdataV4Count } from './OdataV4Count';

/**
 * The links to other resources that are related to this resource.
 * @version 1.13.0
 */
export interface SoftwareInventoryLinks {
    /** An array of devices where this software image is currently running. */
    readonly ActiveTargets?: readonly OdataV4IdRef[];
    'ActiveTargets@odata.count'?: OdataV4Count;
    /** An array of devices where this software image is staged and ready to be activated. */
    readonly StagedTargets?: readonly OdataV4IdRef[];
    'StagedTargets@odata.count'?: OdataV4Count;
}
