/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { OdataV4Context } from './OdataV4Context';
import type { OdataV4Etag } from './OdataV4Etag';
import type { OdataV4Id } from './OdataV4Id';
import type { OdataV4Type } from './OdataV4Type';
import type { SoftwareInventoryActions } from './SoftwareInventoryActions';
import type { SoftwareInventoryAdditionalVersions } from './SoftwareInventoryAdditionalVersions';
import type { PhysicalContext } from './PhysicalContext';
import type { ResourceDescription } from './ResourceDescription';
import type { ResourceId } from './ResourceId';
import type { SoftwareInventoryLinks } from './SoftwareInventoryLinks';
import type { SoftwareInventoryMeasurementBlock } from './SoftwareInventoryMeasurementBlock';
import type { ResourceName } from './ResourceName';
import type { ResourceOem } from './ResourceOem';
import type { OdataV4IdRef } from './OdataV4IdRef';
import type { OdataV4Count } from './OdataV4Count';
import type { SoftwareInventoryReleaseType } from './SoftwareInventoryReleaseType';
import type { ResourceStatus } from './ResourceStatus';
import type { SoftwareInventoryVersionScheme } from './SoftwareInventoryVersionScheme';

/**
 * The `SoftwareInventory` schema contains an inventory of software components.  This can include software components such as BIOS, BMC firmware, firmware for other devices, system drivers, or provider software.
 * @version 1.13.0
 */
export interface SoftwareInventory {
    '@odata.context'?: OdataV4Context;
    '@odata.etag'?: OdataV4Etag;
    '@odata.id': OdataV4Id;
    '@odata.type': OdataV4Type;
    /** The available actions for this resource. */
    Actions?: SoftwareInventoryActions;
    /**
     * This image is active on one or more devices.
     * @nullable
     */
    readonly Active?: boolean | null;
    /** The additional versions of this software. */
    AdditionalVersions?: SoftwareInventoryAdditionalVersions;
    /** The area or device to which the software applies.  Used to distinguish when different parts of a device have different software components. */
    readonly AssociatedPhysicalContext?: PhysicalContext;
    /** @nullable */
    readonly Description?: ResourceDescription;
    readonly Id: ResourceId;
    /**
     * The URI at which to access the software inventory image.
     * @nullable
     */
    readonly ImageDataURI?: string | null;
    /** The links to other resources that are related to this resource. */
    Links?: SoftwareInventoryLinks;
    /**
     * The lowest supported version of this software.
     * @nullable
     */
    readonly LowestSupportedVersion?: string | null;
    /**
     * The manufacturer or producer of this software.
     * @nullable
     */
    readonly Manufacturer?: string | null;
    /**
     * A DSP0274-defined measurement block.
     * @deprecated
     */
    Measurement?: SoftwareInventoryMeasurementBlock;
    readonly Name: ResourceName;
    /** The OEM extension property. */
    Oem?: ResourceOem;
    /** An array of links to resources or objects that represent devices to which this software inventory applies. */
    readonly RelatedItem?: readonly OdataV4IdRef[];
    'RelatedItem@odata.count'?: OdataV4Count;
    /**
     * The release date of this software.
     * @nullable
     */
    readonly ReleaseDate?: string | null;
    /**
     * The type of release.
     * @nullable
     */
    readonly ReleaseType?: SoftwareInventoryReleaseType;
    /**
     * An indication of whether a reset is required to apply an update to this software.
     * @nullable
     */
    readonly ResetRequiredOnUpdate?: boolean | null;
    /**
     * The size of the software image in bytes.
     * @nullable
     */
    readonly SizeBytes?: number | null;
    /** The implementation-specific label that identifies this software. */
    readonly SoftwareId?: string;
    /**
     * This image is ready to be activated to one or more devices.
     * @nullable
     */
    readonly Staged?: boolean | null;
    /** The status and health of the resource and its subordinate or dependent resources. */
    Status?: ResourceStatus;
    /** The list of UEFI device paths of the components associated with this software inventory item. */
    readonly UefiDevicePaths?: readonly (string | null)[];
    /**
     * An indication of whether the update service can update this software.
     * @nullable
     */
    readonly Updateable?: boolean | null;
    /**
     * The version of this software.
     * @nullable
     */
    readonly Version?: string | null;
    /**
     * The format of the version.
     * @nullable
     */
    readonly VersionScheme?: SoftwareInventoryVersionScheme;
    /**
     * Indicates if the software is write-protected.
     * @nullable
     */
    WriteProtected?: boolean | null;
}
