/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.13.0
 */
export type SoftwareInventoryVersionScheme =
    (typeof SoftwareInventoryVersionScheme)[keyof typeof SoftwareInventoryVersionScheme];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SoftwareInventoryVersionScheme = {
    /** Version follows Semantic Versioning 2.0 rules. */
    SemVer: 'SemVer',
    /** Version formatted as dot-separated integers. */
    DotIntegerNotation: 'DotIntegerNotation',
    /** Version follows OEM-defined format. */
    OEM: 'OEM',
} as const;
