/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * @version 1.13.0
 */
export type SoftwareInventoryReleaseType =
    (typeof SoftwareInventoryReleaseType)[keyof typeof SoftwareInventoryReleaseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SoftwareInventoryReleaseType = {
    /** This release is ready for use in production environments. */
    Production: 'Production',
    /** This release is intended for development or internal use. */
    Prototype: 'Prototype',
    /** The Redfish service does not have enough data to make a determination about this release. */
    Other: 'Other',
} as const;
