/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */

/**
 * The DSP0274-defined measurement block information.
 * @version 1.13.0
 */
export interface SoftwareInventoryMeasurementBlock {
    /**
     * The hexadecimal string representation of the numeric value of the DSP0274-defined 'Measurement' field of the measurement block.
     * @nullable
     * @pattern ^[0-9a-fA-F]+$
     */
    readonly Measurement?: string | null;
    /**
     * The DSP0274-defined 'Index' field of the measurement block.
     * @nullable
     */
    readonly MeasurementIndex?: number | null;
    /**
     * The DSP0274-defined 'MeasurementSize' field of the measurement block.
     * @nullable
     */
    readonly MeasurementSize?: number | null;
    /**
     * The DSP0274-defined 'MeasurementSpecification' field of the measurement block.
     * @nullable
     */
    readonly MeasurementSpecification?: number | null;
}
