/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { SoftwareInventoryActivate } from './SoftwareInventoryActivate';
import type { SoftwareInventoryOemActions } from './SoftwareInventoryOemActions';

/**
 * The available actions for this resource.
 * @version 1.13.0
 */
export interface SoftwareInventoryActions {
    '#SoftwareInventory.Activate'?: SoftwareInventoryActivate;
    /** The available OEM-specific actions for this resource. */
    Oem?: SoftwareInventoryOemActions;
}
