/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import type { ResourceOem } from './ResourceOem';

/**
 * Additional versions.
 * @version 1.13.0
 */
export interface SoftwareInventoryAdditionalVersions {
    /**
     * The version of the configuration file that contains the initial boot parameters of this software, such as parameters for U-Boot.
     * @nullable
     */
    readonly BootParameters?: string | null;
    /**
     * The bootloader version contained in this software, such as U-Boot or UEFI.
     * @nullable
     */
    readonly Bootloader?: string | null;
    /**
     * The version of the configuration that contains the factory default runtime configuration parameters of this software.
     * @nullable
     */
    readonly FactoryConfiguration?: string | null;
    /**
     * The kernel version contained in this software.
     * @nullable
     */
    readonly Kernel?: string | null;
    /**
     * The microcode version contained in this software, such as processor microcode.
     * @nullable
     */
    readonly Microcode?: string | null;
    /**
     * The operating system name of this software.
     * @nullable
     */
    readonly OSDistribution?: string | null;
    /** The OEM extension property. */
    Oem?: ResourceOem;
}
