/**
 * Minimal endpoints file - contains only exports used by the app.
 *
 * Generated by: scripts/api/generate-dist-endpoints.ts
 * Hooks: 3
 * Total exports: 12
 *
 * For full API, use redfish.gen.ts (development only)
 */

/**
 * Generated by orval v7.19.0 🍺
 * Do not edit manually.
 * Redfish
 * This contains the definition of a Redfish service.
 * OpenAPI spec version: 2025.4
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/vue-query';
import type {
    DataTag,
    InfiniteData,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UseInfiniteQueryOptions,
    UseInfiniteQueryReturnType,
    UseMutationOptions,
    UseMutationReturnType,
    UseQueryOptions,
    UseQueryReturnType,
} from '@tanstack/vue-query';

import { computed, unref } from 'vue';
import type { MaybeRef } from 'vue';

import type {
    AccelerationFunction,
    AccelerationFunctionCollection,
    AccountService,
    AddressPool,
    AddressPoolCollection,
    Aggregate,
    AggregateAddElementsRequestBody,
    AggregateCollection,
    AggregateRemoveElementsRequestBody,
    AggregateResetRequestBody,
    AggregateSetDefaultBootOrderRequestBody,
    AggregationService,
    AggregationServiceResetRequestBody,
    AggregationServiceSetDefaultBootOrderRequestBody,
    AggregationSource,
    AggregationSourceCollection,
    AggregationSourceGenerateSSHIdentityKeyPairRequestBody,
    AggregationSourceRemoveSSHIdentityKeyPairRequestBody,
    AllowDeny,
    AllowDenyCollection,
    Application,
    ApplicationCollection,
    ApplicationResetRequestBody,
    Assembly,
    AutomationInstrumentation,
    AutomationNode,
    AutomationNodeCollection,
    AutomationNodeResetRequestBody,
    AutomationNodeSendTriggerRequestBody,
    AutomationNodeStartRequestBody,
    AutomationNodeStopRequestBody,
    AutomationNodeWaitRequestBody,
    Battery,
    BatteryCalibrateRequestBody,
    BatteryCollection,
    BatteryMetrics,
    BatteryResetRequestBody,
    BatterySelfTestRequestBody,
    Bios,
    BiosChangePasswordRequestBody,
    BiosResetBiosRequestBody,
    BootOption,
    BootOptionCollection,
    CXLLogicalDevice,
    CXLLogicalDeviceCollection,
    CXLLogicalDeviceDisablePassphraseRequestBody,
    CXLLogicalDeviceFreezeSecurityStateRequestBody,
    CXLLogicalDevicePassphraseSecureEraseRequestBody,
    CXLLogicalDeviceSetPassphraseRequestBody,
    CXLLogicalDeviceUnlockRequestBody,
    Cable,
    CableCollection,
    Certificate,
    CertificateCollection,
    CertificateEnrollment,
    CertificateEnrollmentCollection,
    CertificateForceAutomaticRenewRequestBody,
    CertificateLocations,
    CertificateRekeyRequestBody,
    CertificateRekeyResponse,
    CertificateRenewRequestBody,
    CertificateRenewResponse,
    CertificateService,
    CertificateServiceGenerateCSRRequestBody,
    CertificateServiceGenerateCSRResponse,
    CertificateServiceReplaceCertificateRequestBody,
    Chassis,
    ChassisCollection,
    ChassisResetRequestBody,
    Circuit,
    CircuitBreakerControlRequestBody,
    CircuitCollection,
    CircuitPowerControlRequestBody,
    CircuitResetMetricsRequestBody,
    ComponentIntegrity,
    ComponentIntegrityCollection,
    ComponentIntegritySPDMGetSignedMeasurementsRequestBody,
    ComponentIntegritySPDMGetSignedMeasurementsResponse,
    ComponentIntegrityTPMGetSignedMeasurementsRequestBody,
    ComponentIntegrityTPMGetSignedMeasurementsResponse,
    CompositionReservation,
    CompositionReservationCollection,
    CompositionService,
    CompositionServiceComposeRequestBody,
    CompositionServiceComposeResponse,
    ComputerSystem,
    ComputerSystemAddResourceBlockRequestBody,
    ComputerSystemCollection,
    ComputerSystemDecommissionRequestBody,
    ComputerSystemExportConfigurationRequestBody,
    ComputerSystemRemoveResourceBlockRequestBody,
    ComputerSystemResetRequestBody,
    ComputerSystemSetDefaultBootOrderRequestBody,
    Connection,
    ConnectionAddVolumeInfoRequestBody,
    ConnectionCollection,
    ConnectionMethod,
    ConnectionMethodCollection,
    ConnectionRemoveVolumeInfoRequestBody,
    Container,
    ContainerCollection,
    ContainerImage,
    ContainerImageCollection,
    ContainerResetRequestBody,
    Control,
    ControlCollection,
    ControlResetToDefaultsRequestBody,
    CoolantConnector,
    CoolantConnectorCollection,
    CoolantConnectorValveControlRequestBody,
    CoolingLoop,
    CoolingLoopCollection,
    CoolingUnit,
    CoolingUnitCollection,
    CoolingUnitExportConfigurationRequestBody,
    CoolingUnitSetModeRequestBody,
    Drive,
    DriveCollection,
    DriveFreezePersonalityRequestBody,
    DriveGetPersonalityNonceRequestBody,
    DriveGetPersonalityNonceResponse,
    DriveMetrics,
    DriveResetRequestBody,
    DriveRevertPersonalitiesToDefaultsRequestBody,
    DriveRevertToOriginalFactoryStateRequestBody,
    DriveSecureEraseRequestBody,
    DriveSetPersonalityKeyRequestBody,
    DriveUnfreezePersonalityRequestBody,
    Endpoint,
    EndpointCollection,
    EndpointGroup,
    EndpointGroupCollection,
    EnvironmentMetrics,
    EnvironmentMetricsResetMetricsRequestBody,
    EnvironmentMetricsResetToDefaultsRequestBody,
    EthernetInterface,
    EthernetInterfaceCollection,
    EventDestination,
    EventDestinationCollection,
    EventDestinationResumeSubscriptionRequestBody,
    EventDestinationSuspendSubscriptionRequestBody,
    EventService,
    EventServiceSubmitTestEventRequestBody,
    EventServiceTestEventSubscriptionRequestBody,
    ExternalAccountProvider,
    ExternalAccountProviderCollection,
    Fabric,
    FabricAdapter,
    FabricAdapterCollection,
    FabricCollection,
    Facility,
    FacilityCollection,
    Fan,
    FanCollection,
    Filter,
    FilterCollection,
    Getodata200,
    GraphicsController,
    GraphicsControllerCollection,
    Heater,
    HeaterCollection,
    HeaterMetrics,
    HeaterMetricsResetMetricsRequestBody,
    HostInterface,
    HostInterfaceCollection,
    Job,
    JobCancelRequestBody,
    JobCollection,
    JobDocument,
    JobDocumentCollection,
    JobDocumentSubmitJobRequestBody,
    JobExecutor,
    JobExecutorCollection,
    JobForceStartRequestBody,
    JobInvalidateRequestBody,
    JobResubmitRequestBody,
    JobResumeRequestBody,
    JobService,
    JobServiceCancelAllJobsRequestBody,
    JobSuspendRequestBody,
    JobValidateRequestBody,
    JsonSchemaFile,
    JsonSchemaFileCollection,
    Key,
    KeyCollection,
    KeyPolicy,
    KeyPolicyCollection,
    KeyService,
    LeakDetection,
    LeakDetector,
    LeakDetectorCollection,
    License,
    LicenseCollection,
    LicenseService,
    LicenseServiceInstallRequestBody,
    LogEntry,
    LogEntryCollection,
    LogService,
    LogServiceClearLogRequestBody,
    LogServiceCollectDiagnosticDataRequestBody,
    LogServiceCollection,
    LogServiceDownloadRawLogRequestBody,
    LogServiceDownloadRawLogResponse,
    LogServicePushDiagnosticDataRequestBody,
    Manager,
    ManagerAccount,
    ManagerAccountChangePasswordRequestBody,
    ManagerAccountClearSecretKeyRequestBody,
    ManagerAccountCollection,
    ManagerAccountGenerateSecretKeyRequestBody,
    ManagerAccountGenerateSecretKeyResponse,
    ManagerAccountVerifyTimeBasedOneTimePasswordRequestBody,
    ManagerCollection,
    ManagerDiagnosticData,
    ManagerDiagnosticDataResetMetricsRequestBody,
    ManagerForceFailoverRequestBody,
    ManagerModifyRedundancySetRequestBody,
    ManagerNetworkProtocol,
    ManagerResetRequestBody,
    ManagerResetToDefaultsRequestBody,
    ManagerUpdateSecurityModeRequestBody,
    MediaController,
    MediaControllerCollection,
    MediaControllerResetRequestBody,
    Memory,
    MemoryChunks,
    MemoryChunksCollection,
    MemoryCollection,
    MemoryDisableMasterPassphraseRequestBody,
    MemoryDisablePassphraseRequestBody,
    MemoryDomain,
    MemoryDomainCollection,
    MemoryFreezeSecurityStateRequestBody,
    MemoryInjectPersistentPoisonRequestBody,
    MemoryMetrics,
    MemoryMetricsClearCurrentPeriodRequestBody,
    MemoryOverwriteUnitRequestBody,
    MemoryRegion,
    MemoryRegionCollection,
    MemoryResetRequestBody,
    MemoryResetToDefaultsRequestBody,
    MemoryScanMediaRequestBody,
    MemorySecureEraseUnitRequestBody,
    MemorySetMasterPassphraseRequestBody,
    MemorySetPassphraseRequestBody,
    MemoryUnlockUnitRequestBody,
    MessageRegistryFile,
    MessageRegistryFileCollection,
    MetricDefinition,
    MetricDefinitionCollection,
    MetricReport,
    MetricReportCollection,
    MetricReportDefinition,
    MetricReportDefinitionCollection,
    NetworkAdapter,
    NetworkAdapterCollection,
    NetworkAdapterMetrics,
    NetworkAdapterMetricsResetMetricsRequestBody,
    NetworkAdapterResetRequestBody,
    NetworkAdapterResetSettingsToDefaultRequestBody,
    NetworkDeviceFunction,
    NetworkDeviceFunctionCollection,
    NetworkDeviceFunctionMetrics,
    NetworkDeviceFunctionMetricsResetMetricsRequestBody,
    NetworkInterface,
    NetworkInterfaceCollection,
    NetworkPort,
    NetworkPortCollection,
    OperatingConfig,
    OperatingConfigCollection,
    OperatingSystem,
    OutboundConnection,
    OutboundConnectionCollection,
    Outlet,
    OutletCollection,
    OutletGroup,
    OutletGroupCollection,
    OutletGroupPowerControlRequestBody,
    OutletGroupResetMetricsRequestBody,
    OutletPowerControlRequestBody,
    OutletResetMetricsRequestBody,
    PCIeDevice,
    PCIeDeviceCollection,
    PCIeFunction,
    PCIeFunctionCollection,
    PCIeSlots,
    Port,
    PortCollection,
    PortMetrics,
    PortMetricsResetMetricsRequestBody,
    PortResetPPBRequestBody,
    PortResetRequestBody,
    Power,
    PowerDistribution,
    PowerDistributionCollection,
    PowerDistributionExportConfigurationRequestBody,
    PowerDistributionMetrics,
    PowerDistributionMetricsResetMetricsRequestBody,
    PowerDistributionTransferControlRequestBody,
    PowerDomain,
    PowerDomainCollection,
    PowerEquipment,
    PowerSubsystem,
    PowerSupply,
    PowerSupplyCollection,
    PowerSupplyMetrics,
    PowerSupplyMetricsResetMetricsRequestBody,
    PowerSupplyResetRequestBody,
    Processor,
    ProcessorCollection,
    ProcessorMetrics,
    ProcessorMetricsClearCurrentPeriodRequestBody,
    ProcessorResetRequestBody,
    ProcessorResetToDefaultsRequestBody,
    Pump,
    PumpCollection,
    PumpSetModeRequestBody,
    RedfishError,
    RegisteredClient,
    RegisteredClientCollection,
    Reservoir,
    ReservoirCollection,
    ResourceBlock,
    ResourceBlockCollection,
    Role,
    RoleCollection,
    RouteEntry,
    RouteEntryCollection,
    RouteSetEntry,
    RouteSetEntryCollection,
    SecureBoot,
    SecureBootDatabase,
    SecureBootDatabaseCollection,
    SecureBootDatabaseResetKeysRequestBody,
    SecureBootResetKeysRequestBody,
    SecurityPolicy,
    Sensor,
    SensorCollection,
    SensorResetMetricsRequestBody,
    SensorResetToDefaultsRequestBody,
    SerialInterface,
    SerialInterfaceCollection,
    ServiceConditions,
    ServiceRoot,
    Session,
    SessionCollection,
    SessionService,
    Signature,
    SignatureCollection,
    SimpleStorage,
    SimpleStorageCollection,
    SoftwareInventory,
    SoftwareInventoryActivateRequestBody,
    SoftwareInventoryCollection,
    Storage,
    StorageCollection,
    StorageController,
    StorageControllerAttachDetachNamespacesResponse,
    StorageControllerAttachNamespacesRequestBody,
    StorageControllerCollection,
    StorageControllerDetachNamespacesRequestBody,
    StorageControllerMetrics,
    StorageControllerResetRequestBody,
    StorageControllerSecurityReceiveRequestBody,
    StorageControllerSecurityReceiveResponse,
    StorageControllerSecuritySendRequestBody,
    StorageFreezePersonalityRequestBody,
    StorageGetPersonalityNonceRequestBody,
    StorageGetPersonalityNonceResponse,
    StorageImportForeignDrivesRequestBody,
    StorageMetrics,
    StorageRekeyExternalKeyRequestBody,
    StorageResetToDefaultsRequestBody,
    StorageRevertPersonalitiesToDefaultsRequestBody,
    StorageSetControllerPasswordRequestBody,
    StorageSetEncryptionKeyRequestBody,
    StorageSetPersonalityKeyRequestBody,
    StorageUnfreezePersonalityRequestBody,
    Switch,
    SwitchCollection,
    SwitchMetrics,
    SwitchMetricsClearCurrentPeriodRequestBody,
    SwitchResetRequestBody,
    Task,
    TaskCollection,
    TaskService,
    TaskServiceDeleteAllCompletedTasksRequestBody,
    TelemetryData,
    TelemetryDataCollection,
    TelemetryService,
    TelemetryServiceClearMetricReportsRequestBody,
    TelemetryServiceClearTelemetryDataRequestBody,
    TelemetryServiceCollectTelemetryDataRequestBody,
    TelemetryServiceCollectTelemetryDataResponse,
    TelemetryServiceResetMetricReportDefinitionsToDefaultsRequestBody,
    TelemetryServiceResetTriggersToDefaultsRequestBody,
    TelemetryServiceSubmitTestMetricReportRequestBody,
    Thermal,
    ThermalEquipment,
    ThermalMetrics,
    ThermalMetricsResetMetricsRequestBody,
    ThermalSubsystem,
    Triggers,
    TriggersCollection,
    TrustedComponent,
    TrustedComponentCollection,
    TrustedComponentTPMGetEventLogRequestBody,
    TrustedComponentTPMGetEventLogResponse,
    USBController,
    USBControllerCollection,
    UpdateService,
    UpdateServiceActivateRequestBody,
    UpdateServiceCapabilities,
    UpdateServiceGenerateSSHIdentityKeyPairRequestBody,
    UpdateServiceRemoveSSHIdentityKeyPairRequestBody,
    UpdateServiceSimpleUpdateRequestBody,
    UpdateServiceStartUpdateRequestBody,
    VCATEntry,
    VCATEntryCollection,
    VLanNetworkInterface,
    VLanNetworkInterfaceCollection,
    VirtualCXLSwitch,
    VirtualCXLSwitchCollection,
    VirtualMedia,
    VirtualMediaCollection,
    VirtualMediaEjectMediaRequestBody,
    VirtualMediaInsertMediaRequestBody,
    VirtualPCI2PCIBridge,
    VirtualPCI2PCIBridgeCollection,
    Volume,
    VolumeAssignReplicaTargetRequestBody,
    VolumeChangeRAIDLayoutRequestBody,
    VolumeCheckConsistencyRequestBody,
    VolumeCollection,
    VolumeCreateReplicaTargetRequestBody,
    VolumeForceEnableRequestBody,
    VolumeInitializeRequestBody,
    VolumeRemoveReplicaRelationshipRequestBody,
    VolumeResumeReplicationRequestBody,
    VolumeReverseReplicationRelationshipRequestBody,
    VolumeSplitReplicationRequestBody,
    VolumeSuspendReplicationRequestBody,
    Zone,
    ZoneAddEndpointRequestBody,
    ZoneCollection,
    ZoneRemoveEndpointRequestBody,
} from '../model';

import { apiInstance } from '../mutator/axios-instance';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
    (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
    [P in keyof T]-?: IfEquals<
        { [Q in P]: T[P] },
        { -readonly [Q in P]: T[P] },
        P
    >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
    k: infer I,
) => void
    ? I
    : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
    ? {
          [P in keyof Writable<T>]: T[P] extends object
              ? NonReadonly<NonNullable<T[P]>>
              : T[P];
      }
    : DistributeReadOnlyOverUnions<T>;


export const getAccountService = (signal?: AbortSignal) => {
    return apiInstance<AccountService>({
        url: `/redfish/v1/AccountService`,
        method: 'GET',
        signal,
    });
};

export const getGetAccountServiceQueryKey = () => {
    return ['redfish', 'v1', 'AccountService'] as const;
};

export const getGetAccountServiceQueryOptions = <
    TData = Awaited<ReturnType<typeof getAccountService>>,
    TError = RedfishError,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getAccountService>>,
            TError,
            TData
        >
    >;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = getGetAccountServiceQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAccountService>>
    > = ({ signal }) => getAccountService(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getAccountService>>,
        TError,
        TData
    >;
};

export type GetAccountServiceQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAccountService>>
>;
export type GetAccountServiceQueryError = RedfishError;

export function useGetAccountService<
    TData = Awaited<ReturnType<typeof getAccountService>>,
    TError = RedfishError,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAccountService>>,
                TError,
                TData
            >
        >;
    },
    queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAccountServiceQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = unref(queryOptions).queryKey as DataTag<
        QueryKey,
        TData,
        TError
    >;

    return query;
}

export const patchAccountService = (
    accountService: MaybeRef<NonReadonly<AccountService>>,
) => {
    accountService = unref(accountService);

    return apiInstance<AccountService | Task | void>({
        url: `/redfish/v1/AccountService`,
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        data: accountService,
    });
};

export const getPatchAccountServiceMutationOptions = <
    TError = RedfishError,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchAccountService>>,
        TError,
        { data: NonReadonly<AccountService> },
        TContext
    >;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchAccountService>>,
    TError,
    { data: NonReadonly<AccountService> },
    TContext
> => {
    const mutationKey = ['patchAccountService'];
    const { mutation: mutationOptions } = options
        ? options.mutation &&
          'mutationKey' in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey } };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchAccountService>>,
        { data: NonReadonly<AccountService> }
    > = (props) => {
        const { data } = props ?? {};

        return patchAccountService(data);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchAccountServiceMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchAccountService>>
>;
export type PatchAccountServiceMutationBody = NonReadonly<AccountService>;
export type PatchAccountServiceMutationError = RedfishError;

export const usePatchAccountService = <
    TError = RedfishError,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchAccountService>>,
            TError,
            { data: NonReadonly<AccountService> },
            TContext
        >;
    },
    queryClient?: QueryClient,
): UseMutationReturnType<
    Awaited<ReturnType<typeof patchAccountService>>,
    TError,
    { data: NonReadonly<AccountService> },
    TContext
> => {
    const mutationOptions = getPatchAccountServiceMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};

